// Selections available when using the Samples app, used by Script Links page
var sampleScriptsIndex = {  
    'adlm': { name: "Adlam", langs:['fuf-adlm'], font:['adlm']},
    'ahom': { name: "Ahom", langs:['pi-ahom'], font:['ahom']}, 
    'arab': { name: "Arabic", langs:['arb','ha-arab','ks-arab', 'fa', 'ur'], font:['arab', 'arab-afr', 'arab&style=nastaliq',]}, 
    'armn': { name: "Armenian", langs:['hy'], font: ['armn'] },
    'armi': { name: "Imperial Aramaic", langs:['arc'], font: ['armi'] },
    'avst': { name: "Avestan", langs:['ae'], font: ['avst'] },
    'bali': { name: "Balinese", langs:['ban'], font: ['bali'] }, 
    'bamu': { name: "Bamum", langs:['bax'], font: ['bamu'] }, 
    'bass': { name: "Bassa Vah", langs:['bsq'], font: ['bass'] }, 
    'batk': { name: "Batak", langs:['bbc'], font: ['batk'] }, 
    'beng': { name: "Bengali", langs:['bn'], font: ['beng'] },
    'bhks': { name: "Bhaiksuki", langs:['sa-bhks'], font: ['bhks'] },
    'brah': { name: "Brahmi", langs:['pra'], font: ['brah'] },
    'bugi': { name: "Buginese", langs:['bug'], font: ['bugi'] },
    'buhd': { name: "Buhid", langs:['bku-buhd'], font: ['buhd'] },
    'cans': { name: "UCAS", langs:['ike', 'crk'], font:['cans'] },
    'cakm': { name: "Chakma", langs:['ccp'], font: ['cakm'] },
    'cari': { name: "Carian", langs:['xcr'], font: ['cari'] },
    'cham': { name: "Cham", langs:['pi-cham'], font: ['cham'] },
    'cher': { name: "Cherokee", langs:['chr', 'chr-x-lc'], font:['cher'] },
    'chrs': { name: "Chorasmian", langs:['xco'], font:['chrs'] },
    'copt': { name: "Coptic", langs:['cop'], font: ['copt'] },
    'xsux': { name: "Cuneiform", langs:['akk'], font: ['xsux'] },
    'cpmn': { name: "Cypro Minoan", langs:['omn'], font: ['cpmn'] },
    'cprt': { name: "Cypriot Syllabary", langs:['omn-cprt'], font: ['cprt'] },
    'cyrl': { name: "Cyrillic", langs:['kk', 'ky', 'ru', 'uk'], font: ['cyrl'] },
    'deva': { name: "Devanagari", langs:['hi', 'ks-deva', 'npi'], font:['deva'] },
    'diak': { name: "Dives Akuru", langs:['dv-diak'], font:['diak'] },
    'dogr': { name: "Dogra", langs:['sa-dogr'], font: ['dogr'] },
    'dsrt': { name: "English (Deseret)", langs:['en-dsrt'], font: ['dsrt'] },
    'egyp': { name: "Egyptian hieroglyphs", langs:['egy'], font: ['egyp'] },
    'elba': { name: "Elbasan", langs:['sq-elba'], font: ['elba'] },
    'elym': { name: "Elymaic", langs:['xly'], font: ['elym'] },
    'ethi': { name: "Ethiopic", langs:['am'], font: ['ethi'] },
    'geor': { name: "Georgian", langs:['ka'], font: ['geor'] },
    'glag': { name: "Glagolitic", langs:['cu-glag'], font: ['glag'] },
    'goth': { name: "Gothic", langs:['got'], font: ['goth'] },
    'gran': { name: "Grantha", langs:['sa-gran'], font: ['gran'] },
    'grek': { name: "Greek", langs:['el'], font: ['grek'] },
    'gujr': { name: "Gujarati", langs:['gu'], font: ['gujr'] },
    'gong': { name: "Gunjala Gondi", langs:['gon'], font: ['gong'] },
    'gonm': { name: "Masaram Gondi", langs:['sa-gonm'], font: ['gonm'] },
    'guru': { name: "Gurmukhi", langs:['pa'], font: ['guru'] },
    'hano': { name: "Hanunoo", langs:['hnn'], font: ['hano'] },
    'hani': { name: "Chinese", langs:['zh-hans', 'zh-hant'], font:['hans', 'hant'] },
    'hatr': { name: "Hatran", langs:['mis-Hatr'], font: ['hatr'] },
    'kore': { name: "Hangul", langs:['ko'], font: ['kore'] },
    'hebr': { name: "Hebrew", langs:['he'], font: ['hebr'] },
    'hluw': { name: "Anatolian Hieroglyphs", langs:['hlu'], font: ['hluw'] },
    'hmng': { name: "Pahawh Hmong", langs:['hmn-hmng'], font: ['hmng'] },
    'hmnp': { name: "Nyiakeng Puachue Hmong", langs:['hmn-hmnp'], font: ['hmnp'] },
    'hung': { name: "Old Hungarian", langs:['ohu'], font: ['hung'] },
    'ital': { name: "Old Italic", langs:['ett'], font: ['ital'] },
    'jpan': { name: "Japanese", langs:['ja'], font: ['jpan'] },
    'java': { name: "Javanese", langs:['jv'], font: ['java'] },
    'kali': { name: "Kayah Li", langs:['kar-kali'], font: ['kali'] },
    'kawi': { name: "Kawi", langs:['kaw'], font: ['kawi'] },
    'khmr': { name: "Khmer", langs:['km'], font: ['khmr'] },
    'khar': { name: "Kharoshthi", langs:['pgd'], font: ['khar'] },
    'kits': { name: "Khitan Small Script", langs:['zkt'], font: ['kits'] },
    'knda': { name: "Kannada", langs:['kn'], font: ['knda'] },
    'krai': { name: "Kirat Rai", langs:['bap'], font: ['krai'] },
    'kthi': { name: "Kaithi", langs:['und-kthi'], font: ['kthi'] },
    'khoj': { name: "Khojki", langs:['sa-khoj'], font: ['khoj'] },
    'laoo': { name: "Lao", langs:['lo'], font: ['laoo'] },
    'lana': { name: "Tai Tham", langs:['kkh', 'nod'], font:['lana', 'lana-kkh', 'lana-nod'] },
    'latn': { name: "Latin", langs:['ak', 'ang', 'cy', 'dgr', 'en-GB-fonipa', 'ha-NE', 'ha-NG', 'non', 've', 'vi', 'yo'], font:['latn'] },
    'lepc': { name: "Lepcha", langs:['lep'], font: ['lepc'] },
    'limb': { name: "Limbu", langs:['lif'], font: ['limb'] },
    'lina': { name: "Linear A", langs:['omn-lina'], font: ['lina'] },
    'linb': { name: "Linear B", langs:['gmy'], font: ['linb'] },
    'lisu': { name: "Lisu", langs:['lis'], font: ['lisu'] },
    'lyci': { name: "Lycian", langs:['xlc'], font: ['lyci'] },
    'lydi': { name: "Lydian", langs:['xld'], font: ['lydi'] },
    'mahj': { name: "Mahajani", langs:['sa-mahj'], font: ['mahj'] },
    'maka': { name: "Makasar", langs:['mak'], font: ['maka'] },
    'mand': { name: "Mandaic", langs:['mid'], font: ['mand'] },
    'mani': { name: "Manichaean", langs:['xmn'], font: ['mani'] },
    'marc': { name: "Marchen", langs:['sa-marc'], font: ['marc'] },
    'medf': { name: "Medefaidrin", langs:['dmf'], font: ['medf'] },
    'mend': { name: "Mende Kikakui", langs:['men'], font: ['mend'] },
    'merc': { name: "Meroitic", langs:['xmr'], font: ['merc'] },
    'modi': { name: "Modi", langs:['sa-modi'], font: ['modi'] },
    'mong': { name: "Mongolian", langs:['khk'], font: ['mong'] },
    'mlym': { name: "Malayalam", langs:['ml'], font: ['mlym'] },
    'mroo': { name: "Mro", langs:['mro-mroo','sa-mroo'], font: ['mroo'] },
    'mtei': { name: "Meetei Mayek", langs:['mni'], font: ['mtei'] },
    'mult': { name: "Multani", langs:['skr'], font: ['mult'] },
    'mymr': { name: "Myanmar", langs:['my', 'shn'], font:['mymr'] },
    'narb': { name: "Old North Arabian", langs:['mis-narb'], font: ['narb'] },
    'nbat': { name: "Nabataean", langs:['arc-nbat'], font: ['nbat'] },
    'newa': { name: "Newar", langs:['new'], font: ['newa'] },
    'nkoo': { name: "N’Ko", langs:['nqo'], font: ['nkoo'] },
    'nshu': { name: "Nushu", langs:['mis-nshu'], font: ['nshu'] },
    'ogam': { name: "Ogham", langs:['mga'], font: ['ogam'] },
    'osge': { name: "Osage", langs:['osa'], font: ['osge'] },
    'olck': { name: "Ol Chiki", langs:['sat'], font: ['olck'] },
    'orkh': { name: "Old Turkish", langs:['otk'], font: ['orkh'] },
    'orya': { name: "Oriya", langs:['ory'], font: ['orya'] },
    'osma': { name: "Osmanya", langs:['so-osma'], font: ['osma'] },
    'ougr': { name: "Old Uighur", langs:['oui'], font: ['ougr'] },
    'palm': { name: "Palmyrene", langs:['arc-palm'], font: ['palm'] },
    'perm': { name: "Old Permic", langs:['kv'], font: ['perm'] },
    'phag': { name: "PhagsPa", langs:['sa-phag', 'bo-phag'], font:['phag'] },
    'phnx': { name: "Phoenician", langs:['phn'], font: ['phnx'] },
    'phli': { name: "Pahlavi (Inscriptional)", langs:['pal'], font: ['phli'] },
    'phlp': { name: "Pahlavi (Psalter)", langs:['pal-phlp'], font: ['phlp'] },
    'plrd': { name: "Miao", langs:['hmd-plrd'], font: ['plrd'] },
    'prti': { name: "Parthian (Inscriptional)", langs:['xpr'], font: ['prti'] },
    'rjng': { name: "Rejang", langs:['rej'], font: ['rjng'] },
    'rohg': { name: "Hanifi Rohingya", langs:['rhg'], font: ['rohg'] },
    'runr': { name: "Runic", langs:['non-runr'], font: ['runr'] },
    'samr': { name: "Samaritan", langs:['smp'], font: ['samr'] },
    'sarb': { name: "Old South Arabian", langs:['xsa'], font: ['sarb'] },
    'saur': { name: "Saurashtra", langs:['saz'], font: ['saur'] },
    'shaw': { name: "Shavian", langs:['en-shaw'], font: ['shaw'] },
    'shrd': { name: "Sharada", langs:['sa-shrd'], font: ['shrd'] },
    'sidd': { name: "Siddham", langs:['sa-sidd'], font: ['sidd'] },
    'sind': { name: "Khudawadi", langs:['sa-sind'], font: ['sind'] },
    'sinh': { name: "Sinhala", langs:['si'], font: ['sinh'] },
    'sogd': { name: "Sogdian", langs:['sog'], font: ['sogd'] },
    'sora': { name: "Sora Sompeng", langs:['sa-sora'], font: ['sora'] },
    'soyo': { name: "Soyombo", langs:['sa-soyo'], font: ['soyo'] },
    'sund': { name: "Sundanese", langs:['su'], font: ['sund'] },
    'sylo': { name: "Syloti Nagri", langs:['syl'], font: ['sylo'] },
    'syrc': { name: "Syriac", langs:['aii', 'syc', 'tru'], font:['syrc', 'syrc-aii', 'syrc-tru','syrc-syc'] },
    'tale': { name: "Tai Le", langs:['tdd'], font: ['tale'] },
    'tagb': { name: "Tagbanwa", langs:['tbw'], font: ['tagb'] },
    'takr': { name: "Takri", langs:['sa-takr'], font: ['takr'] },
    'talu': { name: "New Tai Lü", langs:['khb'], font: ['talu'] },
    'taml': { name: "Tamil", langs:['ta'], font: ['taml'] },
    'tang': { name: "Tangut", langs:['txg'], font: ['tang'] },
    'tavt': { name: "Tai Viet", langs:['blt'], font: ['tavt'] },
    'telu': { name: "Telugu", langs:['te'], font: ['telu'] },
    'tglg': { name: "Tagalog", langs:['tgl'], font: ['tglg'] },
    'thaa': { name: "Thaana", langs:['dv'], font: ['thaa'] },
    'thai': { name: "Thai", langs:['th'], font: ['thai'] },
    'tibt': { name: "Tibetan", langs:['bo', 'dz'], font:['tibt'] },
    'tirh': { name: "Tirhuta", langs:['sa-tirh'], font: ['tirh'] },
    'tfng': { name: "Tifinagh", langs:['zgh'], font: ['tfng'] },
    'tnsa': { name: "Tangsa", langs:['nst'], font: ['tnsa'] },
    'toto': { name: "Toto", langs:['txo'], font: ['toto'] },
    'ugar': { name: "Ugaritic", langs:['uga'], font: ['ugar'] },
    'vaii': { name: "Vai", langs:['vai'], font: ['vaii'] },
    'vith': { name: "Vithkuqi", langs:['sq-vith'], font: ['vith'] },
    'wara': { name: "Warang Citi", langs:['hoc'], font: ['wara'] },
    'wcho': { name: "Wancho", langs:['sa-wcho'], font: ['wcho'] },
    'xpeo': { name: "Old Persian", langs:['peo'], font: ['xpeo'] },
    'aghb': { name: "Caucasian Albanian", langs:['cau'], font: ['aghb'] },
    'yiii': { name: "Yi", langs:['ii'], font: ['yiii'] },
    'zanb': { name: "Zanabazar Square", langs:['sa-zanb'], font: ['zanb'] },
    'yezi': { name: "Yezidi", langs:['ku-yezi'], font: ['yezi'] },
    }
