// Selections available when using the Samples app, used by Script Links page
var sampleScriptsIndex = {  
    'adlm': { name: "Adlam", langs:['fuf-adlm']},
    'arab': { name: "Arabic", langs:['arb','ha-arab','ks-arab', 'fa', 'ur']}, 
    'armn': { name: "Armenian", langs:['hy']},
    'armi': { name: "Imperial Aramaic", langs:['arc']},
    'bali': { name: "Balinese", langs:['ban']}, 
    'bamu': { name: "Bamum", langs:['bax']}, 
    'bass': { name: "Bassa Vah", langs:['bsq']}, 
    'beng': { name: "Bengali", langs:['bn']},
    'bugi': { name: "Buginese", langs:['bug']},
    'buhd': { name: "Buhid", langs:['bku-buhd']},
    'cans': { name: "UCAS", langs:['ike', 'crk']},
    'cakm': { name: "Chakma", langs:['ccp']},
    'cher': { name: "Cherokee", langs:['chr', 'chr-x-lc']},
    'copt': { name: "Coptic", langs:['cop']},
    'cyrl': { name: "Cyrillic", langs:['kk', 'ky', 'ru']},
    'deva': { name: "Devanagari", langs:['hi', 'ks-deva', 'npi']},
    'ethi': { name: "Ethiopic", langs:['am']},
    'geor': { name: "Georgian", langs:['ka']},
    'grek': { name: "Greek", langs:['el']},
    'gujr': { name: "Gujarati", langs:['gu']},
    'gong': { name: "Gunjala Gondi", langs:['gon']},
    'guru': { name: "Gurmukhi", langs:['pa']},
    'hano': { name: "Hanunoo", langs:['hnn']},
    'hani': { name: "Chinese", langs:['zh-hans', 'zh-hant']},
    'kore': { name: "Hangul", langs:['ko']},
    'hebr': { name: "Hebrew", langs:['he']},
    'hung': { name: "Old Hungarian", langs:['ohu']},
    'jpan': { name: "Japanese", langs:['ja']},
    'java': { name: "Javanese", langs:['jv']},
    'khmr': { name: "Khmer", langs:['km']},
    'knda': { name: "Kannada", langs:['kn']},
    'laoo': { name: "Lao", langs:['lo']},
    'lana': { name: "Tai Tham", langs:['kkh', 'nod']},
    'latn': { name: "Latin", langs:['ak', 'cy', 'dgr', 'en-GB-fonipa', 'ha-NE', 'ha-NG', 've', 'vi', 'yo']},
    'lepc': { name: "Lepcha", langs:['lep']},
    'limb': { name: "Limbu", langs:['lif']},
    'lisu': { name: "Lisu", langs:['lis']},
    'maka': { name: "Makasar", langs:['mak']},
    'mand': { name: "Mandaic", langs:['mid']},
    'mend': { name: "Mende Kikakui", langs:['men']},
    'mong': { name: "Mongolian", langs:['khk']},
    'mlym': { name: "Malayalam", langs:['ml']},
    'mtei': { name: "Meetei Mayek", langs:['mni']},
    'mymr': { name: "Myanmar", langs:['my', 'shn']},
    'newa': { name: "Newar", langs:['new']},
    'nkoo': { name: "N’Ko", langs:['nqo']},
    'osge': { name: "Osage", langs:['osa']},
    'olck': { name: "Ol Chiki", langs:['sat']},
    'orya': { name: "Oriya", langs:['ory']},
    'osma': { name: "Osmanya", langs:['so-osma']},
    'phag': { name: "PhagsPa", langs:['sa-phag']},
    'phnx': { name: "Phoenician", langs:['phn']},
    'rohg': { name: "Hanifi Rohingya", langs:['rhg']},
    'runr': { name: "Runic", langs:['non-runr']},
    'samr': { name: "Samaritan", langs:['smp']},
    'saur': { name: "Saurashtra", langs:['saz']},
    'shaw': { name: "Shavian", langs:['en-shaw']},
    'sinh': { name: "Sinhala", langs:['si']},
    'sund': { name: "Sundanese", langs:['su']},
    'syrc': { name: "Syriac", langs:['aii', 'syc', 'tru']},
    'tale': { name: "Tai Le", langs:['tdd']},
    'tagb': { name: "Tagbanwa", langs:['tbw']},
    'talu': { name: "New Tai Lü", langs:['khb']},
    'taml': { name: "Tamil", langs:['ta']},
    'telu': { name: "Telugu", langs:['te']},
    'tavt': { name: "Tai Viet", langs:['blt']},
    'thaa': { name: "Thaana", langs:['dv']},
    'thai': { name: "Thai", langs:['th']},
    'tibt': { name: "Tibetan", langs:['bo', 'dz']},
    'tfng': { name: "Tifinagh", langs:['zgh']},
    'vaii': { name: "Vai", langs:['vai']},
    'yiii': { name: "Yi", langs:['ii']},
    }
