var spreadsheet = `
᐀		dash punctuation		U+1400: CANADIAN SYLLABICS HYPHEN	
ᐁ		syllable		U+1401: CANADIAN SYLLABICS E	🗸
ᐂ		syllable		U+1402: CANADIAN SYLLABICS AAI	
ᐃ		syllable		U+1403: CANADIAN SYLLABICS I	🗸
ᐄ		syllable		U+1404: CANADIAN SYLLABICS II	🗸
ᐅ		syllable		U+1405: CANADIAN SYLLABICS O	🗸
ᐆ		syllable		U+1406: CANADIAN SYLLABICS OO	🗸
ᐇ		syllable		U+1407: CANADIAN SYLLABICS Y-CREE OO	
ᐈ		syllable		U+1408: CANADIAN SYLLABICS CARRIER EE	
ᐉ		syllable		U+1409: CANADIAN SYLLABICS CARRIER I	
ᐊ		syllable		U+140A: CANADIAN SYLLABICS A	🗸
ᐋ		syllable		U+140B: CANADIAN SYLLABICS AA	🗸
ᐌ		syllable		U+140C: CANADIAN SYLLABICS WE	
ᐍ		syllable		U+140D: CANADIAN SYLLABICS WEST-CREE WE	🗸
ᐎ		syllable		U+140E: CANADIAN SYLLABICS WI	
ᐏ		syllable		U+140F: CANADIAN SYLLABICS WEST-CREE WI	🗸
ᐐ		syllable		U+1410: CANADIAN SYLLABICS WII	
ᐑ		syllable		U+1411: CANADIAN SYLLABICS WEST-CREE WII	🗸
ᐒ		syllable		U+1412: CANADIAN SYLLABICS WO	
ᐓ		syllable		U+1413: CANADIAN SYLLABICS WEST-CREE WO	🗸
ᐔ		syllable		U+1414: CANADIAN SYLLABICS WOO	
ᐕ		syllable		U+1415: CANADIAN SYLLABICS WEST-CREE WOO	🗸
ᐖ		syllable		U+1416: CANADIAN SYLLABICS NASKAPI WOO	
ᐗ		syllable		U+1417: CANADIAN SYLLABICS WA	
ᐘ		syllable		U+1418: CANADIAN SYLLABICS WEST-CREE WA	🗸
ᐙ		syllable		U+1419: CANADIAN SYLLABICS WAA	
ᐚ		syllable		U+141A: CANADIAN SYLLABICS WEST-CREE WAA	🗸
ᐛ		syllable		U+141B: CANADIAN SYLLABICS NASKAPI WAA	
ᐜ		syllable		U+141C: CANADIAN SYLLABICS AI	
ᐝ		letter		U+141D: CANADIAN SYLLABICS Y-CREE W	
ᐞ		letter		U+141E: CANADIAN SYLLABICS GLOTTAL STOP	
ᐟ		final letter		U+141F: CANADIAN SYLLABICS FINAL ACUTE	🗸
ᐠ		final letter		U+1420: CANADIAN SYLLABICS FINAL GRAVE	🗸
ᐡ		final letter		U+1421: CANADIAN SYLLABICS FINAL BOTTOM HALF RING	
ᐢ		final letter		U+1422: CANADIAN SYLLABICS FINAL TOP HALF RING	🗸
ᐣ		final letter		U+1423: CANADIAN SYLLABICS FINAL RIGHT HALF RING	🗸
ᐤ		final letter		U+1424: CANADIAN SYLLABICS FINAL RING	🗸
ᐥ		final letter		U+1425: CANADIAN SYLLABICS FINAL DOUBLE ACUTE	
ᐦ		final letter		U+1426: CANADIAN SYLLABICS FINAL DOUBLE SHORT VERTICAL STROKES	🗸
ᐧ		final letter		U+1427: CANADIAN SYLLABICS FINAL MIDDLE DOT	
ᐨ		final letter		U+1428: CANADIAN SYLLABICS FINAL SHORT HORIZONTAL STROKE	🗸
ᐩ		final letter		U+1429: CANADIAN SYLLABICS FINAL PLUS	
ᐪ		final letter		U+142A: CANADIAN SYLLABICS FINAL DOWN TACK	
ᐫ		syllable		U+142B: CANADIAN SYLLABICS EN	
ᐬ		syllable		U+142C: CANADIAN SYLLABICS IN	
ᐭ		syllable		U+142D: CANADIAN SYLLABICS ON	
ᐮ		syllable		U+142E: CANADIAN SYLLABICS AN	
ᐯ		syllable		U+142F: CANADIAN SYLLABICS PE	🗸
ᐰ		syllable		U+1430: CANADIAN SYLLABICS PAAI	
ᐱ		syllable		U+1431: CANADIAN SYLLABICS PI	🗸
ᐲ		syllable		U+1432: CANADIAN SYLLABICS PII	🗸
ᐳ		syllable		U+1433: CANADIAN SYLLABICS PO	🗸
ᐴ		syllable		U+1434: CANADIAN SYLLABICS POO	🗸
ᐵ		syllable		U+1435: CANADIAN SYLLABICS Y-CREE POO	
ᐶ		syllable		U+1436: CANADIAN SYLLABICS CARRIER HEE	
ᐷ		syllable		U+1437: CANADIAN SYLLABICS CARRIER HI	
ᐸ		syllable		U+1438: CANADIAN SYLLABICS PA	🗸
ᐹ		syllable		U+1439: CANADIAN SYLLABICS PAA	🗸
ᐺ		syllable		U+143A: CANADIAN SYLLABICS PWE	
ᐻ		syllable		U+143B: CANADIAN SYLLABICS WEST-CREE PWE	🗸
ᐼ		syllable		U+143C: CANADIAN SYLLABICS PWI	
ᐽ		syllable		U+143D: CANADIAN SYLLABICS WEST-CREE PWI	🗸
ᐾ		syllable		U+143E: CANADIAN SYLLABICS PWII	
ᐿ		syllable		U+143F: CANADIAN SYLLABICS WEST-CREE PWII	🗸
ᑀ		syllable		U+1440: CANADIAN SYLLABICS PWO	
ᑁ		syllable		U+1441: CANADIAN SYLLABICS WEST-CREE PWO	🗸
ᑂ		syllable		U+1442: CANADIAN SYLLABICS PWOO	
ᑃ		syllable		U+1443: CANADIAN SYLLABICS WEST-CREE PWOO	🗸
ᑄ		syllable		U+1444: CANADIAN SYLLABICS PWA	
ᑅ		syllable		U+1445: CANADIAN SYLLABICS WEST-CREE PWA	🗸
ᑆ		syllable		U+1446: CANADIAN SYLLABICS PWAA	
ᑇ		syllable		U+1447: CANADIAN SYLLABICS WEST-CREE PWAA	🗸
ᑈ		syllable		U+1448: CANADIAN SYLLABICS Y-CREE PWAA	
ᑉ		letter		U+1449: CANADIAN SYLLABICS P	🗸
ᑊ		letter		U+144A: CANADIAN SYLLABICS WEST-CREE P	🗸
ᑋ		letter		U+144B: CANADIAN SYLLABICS CARRIER H	
ᑌ		syllable		U+144C: CANADIAN SYLLABICS TE	🗸
ᑍ		syllable		U+144D: CANADIAN SYLLABICS TAAI	
ᑎ		syllable		U+144E: CANADIAN SYLLABICS TI	🗸
ᑏ		syllable		U+144F: CANADIAN SYLLABICS TII	🗸
ᑐ		syllable		U+1450: CANADIAN SYLLABICS TO	🗸
ᑑ		syllable		U+1451: CANADIAN SYLLABICS TOO	🗸
ᑒ		syllable		U+1452: CANADIAN SYLLABICS Y-CREE TOO	
ᑓ		syllable		U+1453: CANADIAN SYLLABICS CARRIER DEE	
ᑔ		syllable		U+1454: CANADIAN SYLLABICS CARRIER DI	
ᑕ		syllable		U+1455: CANADIAN SYLLABICS TA	🗸
ᑖ		syllable		U+1456: CANADIAN SYLLABICS TAA	🗸
ᑗ		syllable		U+1457: CANADIAN SYLLABICS TWE	
ᑘ		syllable		U+1458: CANADIAN SYLLABICS WEST-CREE TWE	🗸
ᑙ		syllable		U+1459: CANADIAN SYLLABICS TWI	
ᑚ		syllable		U+145A: CANADIAN SYLLABICS WEST-CREE TWI	🗸
ᑛ		syllable		U+145B: CANADIAN SYLLABICS TWII	
ᑜ		syllable		U+145C: CANADIAN SYLLABICS WEST-CREE TWII	🗸
ᑝ		syllable		U+145D: CANADIAN SYLLABICS TWO	
ᑞ		syllable		U+145E: CANADIAN SYLLABICS WEST-CREE TWO	🗸
ᑟ		syllable		U+145F: CANADIAN SYLLABICS TWOO	
ᑠ		syllable		U+1460: CANADIAN SYLLABICS WEST-CREE TWOO	🗸
ᑡ		syllable		U+1461: CANADIAN SYLLABICS TWA	
ᑢ		syllable		U+1462: CANADIAN SYLLABICS WEST-CREE TWA	🗸
ᑣ		syllable		U+1463: CANADIAN SYLLABICS TWAA	
ᑤ		syllable		U+1464: CANADIAN SYLLABICS WEST-CREE TWAA	🗸
ᑥ		syllable		U+1465: CANADIAN SYLLABICS NASKAPI TWAA	
ᑦ		letter		U+1466: CANADIAN SYLLABICS T	🗸
ᑧ		syllable		U+1467: CANADIAN SYLLABICS TTE	
ᑨ		syllable		U+1468: CANADIAN SYLLABICS TTI	
ᑩ		syllable		U+1469: CANADIAN SYLLABICS TTO	
ᑪ		syllable		U+146A: CANADIAN SYLLABICS TTA	
ᑫ		syllable		U+146B: CANADIAN SYLLABICS KE	🗸
ᑬ		syllable		U+146C: CANADIAN SYLLABICS KAAI	
ᑭ		syllable		U+146D: CANADIAN SYLLABICS KI	🗸
ᑮ		syllable		U+146E: CANADIAN SYLLABICS KII	🗸
ᑯ		syllable		U+146F: CANADIAN SYLLABICS KO	🗸
ᑰ		syllable		U+1470: CANADIAN SYLLABICS KOO	🗸
ᑱ		syllable		U+1471: CANADIAN SYLLABICS Y-CREE KOO	
ᑲ		syllable		U+1472: CANADIAN SYLLABICS KA	🗸
ᑳ		syllable		U+1473: CANADIAN SYLLABICS KAA	🗸
ᑴ		syllable		U+1474: CANADIAN SYLLABICS KWE	
ᑵ		syllable		U+1475: CANADIAN SYLLABICS WEST-CREE KWE	🗸
ᑶ		syllable		U+1476: CANADIAN SYLLABICS KWI	
ᑷ		syllable		U+1477: CANADIAN SYLLABICS WEST-CREE KWI	🗸
ᑸ		syllable		U+1478: CANADIAN SYLLABICS KWII	
ᑹ		syllable		U+1479: CANADIAN SYLLABICS WEST-CREE KWII	🗸
ᑺ		syllable		U+147A: CANADIAN SYLLABICS KWO	
ᑻ		syllable		U+147B: CANADIAN SYLLABICS WEST-CREE KWO	🗸
ᑼ		syllable		U+147C: CANADIAN SYLLABICS KWOO	
ᑽ		syllable		U+147D: CANADIAN SYLLABICS WEST-CREE KWOO	🗸
ᑾ		syllable		U+147E: CANADIAN SYLLABICS KWA	
ᑿ		syllable		U+147F: CANADIAN SYLLABICS WEST-CREE KWA	🗸
ᒀ		syllable		U+1480: CANADIAN SYLLABICS KWAA	
ᒁ		syllable		U+1481: CANADIAN SYLLABICS WEST-CREE KWAA	🗸
ᒂ		syllable		U+1482: CANADIAN SYLLABICS NASKAPI KWAA	
ᒃ		letter		U+1483: CANADIAN SYLLABICS K	🗸
ᒄ		letter		U+1484: CANADIAN SYLLABICS KW	
ᒅ		syllable		U+1485: CANADIAN SYLLABICS SOUTH-SLAVEY KEH	
ᒆ		syllable		U+1486: CANADIAN SYLLABICS SOUTH-SLAVEY KIH	
ᒇ		syllable		U+1487: CANADIAN SYLLABICS SOUTH-SLAVEY KOH	
ᒈ		syllable		U+1488: CANADIAN SYLLABICS SOUTH-SLAVEY KAH	
ᒉ		syllable		U+1489: CANADIAN SYLLABICS CE	🗸
ᒊ		syllable		U+148A: CANADIAN SYLLABICS CAAI	
ᒋ		syllable		U+148B: CANADIAN SYLLABICS CI	🗸
ᒌ		syllable		U+148C: CANADIAN SYLLABICS CII	🗸
ᒍ		syllable		U+148D: CANADIAN SYLLABICS CO	🗸
ᒎ		syllable		U+148E: CANADIAN SYLLABICS COO	🗸
ᒏ		syllable		U+148F: CANADIAN SYLLABICS Y-CREE COO	
ᒐ		syllable		U+1490: CANADIAN SYLLABICS CA	🗸
ᒑ		syllable		U+1491: CANADIAN SYLLABICS CAA	🗸
ᒒ		syllable		U+1492: CANADIAN SYLLABICS CWE	
ᒓ		syllable		U+1493: CANADIAN SYLLABICS WEST-CREE CWE	🗸
ᒔ		syllable		U+1494: CANADIAN SYLLABICS CWI	
ᒕ		syllable		U+1495: CANADIAN SYLLABICS WEST-CREE CWI	🗸
ᒖ		syllable		U+1496: CANADIAN SYLLABICS CWII	
ᒗ		syllable		U+1497: CANADIAN SYLLABICS WEST-CREE CWII	🗸
ᒘ		syllable		U+1498: CANADIAN SYLLABICS CWO	
ᒙ		syllable		U+1499: CANADIAN SYLLABICS WEST-CREE CWO	🗸
ᒚ		syllable		U+149A: CANADIAN SYLLABICS CWOO	
ᒛ		syllable		U+149B: CANADIAN SYLLABICS WEST-CREE CWOO	🗸
ᒜ		syllable		U+149C: CANADIAN SYLLABICS CWA	
ᒝ		syllable		U+149D: CANADIAN SYLLABICS WEST-CREE CWA	🗸
ᒞ		syllable		U+149E: CANADIAN SYLLABICS CWAA	
ᒟ		syllable		U+149F: CANADIAN SYLLABICS WEST-CREE CWAA	🗸
ᒠ		syllable		U+14A0: CANADIAN SYLLABICS NASKAPI CWAA	
ᒡ		letter		U+14A1: CANADIAN SYLLABICS C	🗸
ᒢ		letter		U+14A2: CANADIAN SYLLABICS SAYISI TH	
ᒣ		syllable		U+14A3: CANADIAN SYLLABICS ME	🗸
ᒤ		syllable		U+14A4: CANADIAN SYLLABICS MAAI	
ᒥ		syllable		U+14A5: CANADIAN SYLLABICS MI	🗸
ᒦ		syllable		U+14A6: CANADIAN SYLLABICS MII	🗸
ᒧ		syllable		U+14A7: CANADIAN SYLLABICS MO	🗸
ᒨ		syllable		U+14A8: CANADIAN SYLLABICS MOO	🗸
ᒩ		syllable		U+14A9: CANADIAN SYLLABICS Y-CREE MOO	
ᒪ		syllable		U+14AA: CANADIAN SYLLABICS MA	🗸
ᒫ		syllable		U+14AB: CANADIAN SYLLABICS MAA	🗸
ᒬ		syllable		U+14AC: CANADIAN SYLLABICS MWE	
ᒭ		syllable		U+14AD: CANADIAN SYLLABICS WEST-CREE MWE	🗸
ᒮ		syllable		U+14AE: CANADIAN SYLLABICS MWI	
ᒯ		syllable		U+14AF: CANADIAN SYLLABICS WEST-CREE MWI	🗸
ᒰ		syllable		U+14B0: CANADIAN SYLLABICS MWII	
ᒱ		syllable		U+14B1: CANADIAN SYLLABICS WEST-CREE MWII	🗸
ᒲ		syllable		U+14B2: CANADIAN SYLLABICS MWO	
ᒳ		syllable		U+14B3: CANADIAN SYLLABICS WEST-CREE MWO	🗸
ᒴ		syllable		U+14B4: CANADIAN SYLLABICS MWOO	
ᒵ		syllable		U+14B5: CANADIAN SYLLABICS WEST-CREE MWOO	🗸
ᒶ		syllable		U+14B6: CANADIAN SYLLABICS MWA	
ᒷ		syllable		U+14B7: CANADIAN SYLLABICS WEST-CREE MWA	🗸
ᒸ		syllable		U+14B8: CANADIAN SYLLABICS MWAA	
ᒹ		syllable		U+14B9: CANADIAN SYLLABICS WEST-CREE MWAA	🗸
ᒺ		syllable		U+14BA: CANADIAN SYLLABICS NASKAPI MWAA	
ᒻ		letter		U+14BB: CANADIAN SYLLABICS M	🗸
ᒼ		letter		U+14BC: CANADIAN SYLLABICS WEST-CREE M	🗸
ᒽ		letter		U+14BD: CANADIAN SYLLABICS MH	🗸
ᒾ		letter		U+14BE: CANADIAN SYLLABICS ATHAPASCAN M	
ᒿ		syllable		U+14BF: CANADIAN SYLLABICS SAYISI M	
ᓀ		syllable		U+14C0: CANADIAN SYLLABICS NE	🗸
ᓁ		syllable		U+14C1: CANADIAN SYLLABICS NAAI	
ᓂ		syllable		U+14C2: CANADIAN SYLLABICS NI	🗸
ᓃ		syllable		U+14C3: CANADIAN SYLLABICS NII	🗸
ᓄ		syllable		U+14C4: CANADIAN SYLLABICS NO	🗸
ᓅ		syllable		U+14C5: CANADIAN SYLLABICS NOO	🗸
ᓆ		syllable		U+14C6: CANADIAN SYLLABICS Y-CREE NOO	
ᓇ		syllable		U+14C7: CANADIAN SYLLABICS NA	🗸
ᓈ		syllable		U+14C8: CANADIAN SYLLABICS NAA	🗸
ᓉ		syllable		U+14C9: CANADIAN SYLLABICS NWE	
ᓊ		syllable		U+14CA: CANADIAN SYLLABICS WEST-CREE NWE	🗸
ᓋ		syllable		U+14CB: CANADIAN SYLLABICS NWA	
ᓌ		syllable		U+14CC: CANADIAN SYLLABICS WEST-CREE NWA	🗸
ᓍ		syllable		U+14CD: CANADIAN SYLLABICS NWAA	
ᓎ		syllable		U+14CE: CANADIAN SYLLABICS WEST-CREE NWAA	🗸
ᓏ		syllable		U+14CF: CANADIAN SYLLABICS NASKAPI NWAA	
ᓐ		letter		U+14D0: CANADIAN SYLLABICS N	🗸
ᓑ		letter		U+14D1: CANADIAN SYLLABICS CARRIER NG	
ᓒ		letter		U+14D2: CANADIAN SYLLABICS NH	
ᓓ		syllable		U+14D3: CANADIAN SYLLABICS LE	🗸
ᓔ		syllable		U+14D4: CANADIAN SYLLABICS LAAI	
ᓕ		syllable		U+14D5: CANADIAN SYLLABICS LI	🗸
ᓖ		syllable		U+14D6: CANADIAN SYLLABICS LII	🗸
ᓗ		syllable		U+14D7: CANADIAN SYLLABICS LO	🗸
ᓘ		syllable		U+14D8: CANADIAN SYLLABICS LOO	🗸
ᓙ		syllable		U+14D9: CANADIAN SYLLABICS Y-CREE LOO	
ᓚ		syllable		U+14DA: CANADIAN SYLLABICS LA	🗸
ᓛ		syllable		U+14DB: CANADIAN SYLLABICS LAA	🗸
ᓜ		syllable		U+14DC: CANADIAN SYLLABICS LWE	
ᓝ		syllable		U+14DD: CANADIAN SYLLABICS WEST-CREE LWE	
ᓞ		syllable		U+14DE: CANADIAN SYLLABICS LWI	
ᓟ		syllable		U+14DF: CANADIAN SYLLABICS WEST-CREE LWI	
ᓠ		syllable		U+14E0: CANADIAN SYLLABICS LWII	
ᓡ		syllable		U+14E1: CANADIAN SYLLABICS WEST-CREE LWII	
ᓢ		syllable		U+14E2: CANADIAN SYLLABICS LWO	
ᓣ		syllable		U+14E3: CANADIAN SYLLABICS WEST-CREE LWO	
ᓤ		syllable		U+14E4: CANADIAN SYLLABICS LWOO	
ᓥ		syllable		U+14E5: CANADIAN SYLLABICS WEST-CREE LWOO	
ᓦ		syllable		U+14E6: CANADIAN SYLLABICS LWA	
ᓧ		syllable		U+14E7: CANADIAN SYLLABICS WEST-CREE LWA	
ᓨ		syllable		U+14E8: CANADIAN SYLLABICS LWAA	
ᓩ		syllable		U+14E9: CANADIAN SYLLABICS WEST-CREE LWAA	
ᓪ		letter		U+14EA: CANADIAN SYLLABICS L	🗸
ᓫ		syllable		U+14EB: CANADIAN SYLLABICS WEST-CREE L	🗸
ᓬ		medial letter		U+14EC: CANADIAN SYLLABICS MEDIAL L	🗸
ᓭ		syllable		U+14ED: CANADIAN SYLLABICS SE	🗸
ᓮ		syllable		U+14EE: CANADIAN SYLLABICS SAAI	
ᓯ		syllable		U+14EF: CANADIAN SYLLABICS SI	🗸
ᓰ		syllable		U+14F0: CANADIAN SYLLABICS SII	🗸
ᓱ		syllable		U+14F1: CANADIAN SYLLABICS SO	🗸
ᓲ		syllable		U+14F2: CANADIAN SYLLABICS SOO	🗸
ᓳ		syllable		U+14F3: CANADIAN SYLLABICS Y-CREE SOO	
ᓴ		syllable		U+14F4: CANADIAN SYLLABICS SA	🗸
ᓵ		syllable		U+14F5: CANADIAN SYLLABICS SAA	🗸
ᓶ		syllable		U+14F6: CANADIAN SYLLABICS SWE	
ᓷ		syllable		U+14F7: CANADIAN SYLLABICS WEST-CREE SWE	🗸
ᓸ		syllable		U+14F8: CANADIAN SYLLABICS SWI	
ᓹ		syllable		U+14F9: CANADIAN SYLLABICS WEST-CREE SWI	🗸
ᓺ		syllable		U+14FA: CANADIAN SYLLABICS SWII	
ᓻ		syllable		U+14FB: CANADIAN SYLLABICS WEST-CREE SWII	🗸
ᓼ		syllable		U+14FC: CANADIAN SYLLABICS SWO	
ᓽ		syllable		U+14FD: CANADIAN SYLLABICS WEST-CREE SWO	🗸
ᓾ		syllable		U+14FE: CANADIAN SYLLABICS SWOO	
ᓿ		syllable		U+14FF: CANADIAN SYLLABICS WEST-CREE SWOO	🗸
ᔀ		syllable		U+1500: CANADIAN SYLLABICS SWA	
ᔁ		syllable		U+1501: CANADIAN SYLLABICS WEST-CREE SWA	🗸
ᔂ		syllable		U+1502: CANADIAN SYLLABICS SWAA	
ᔃ		syllable		U+1503: CANADIAN SYLLABICS WEST-CREE SWAA	🗸
ᔄ		syllable		U+1504: CANADIAN SYLLABICS NASKAPI SWAA	
ᔅ		letter		U+1505: CANADIAN SYLLABICS S	🗸
ᔆ		letter		U+1506: CANADIAN SYLLABICS ATHAPASCAN S	
ᔇ		letter		U+1507: CANADIAN SYLLABICS SW	
ᔈ		letter		U+1508: CANADIAN SYLLABICS BLACKFOOT S	
ᔉ		letter		U+1509: CANADIAN SYLLABICS MOOSE-CREE SK	
ᔊ		letter		U+150A: CANADIAN SYLLABICS NASKAPI SKW	
ᔋ		syllable		U+150B: CANADIAN SYLLABICS NASKAPI S-W	
ᔌ		syllable		U+150C: CANADIAN SYLLABICS NASKAPI SPWA	
ᔍ		syllable		U+150D: CANADIAN SYLLABICS NASKAPI STWA	
ᔎ		syllable		U+150E: CANADIAN SYLLABICS NASKAPI SKWA	
ᔏ		syllable		U+150F: CANADIAN SYLLABICS NASKAPI SCWA	
ᔐ		syllable		U+1510: CANADIAN SYLLABICS SHE	
ᔑ		syllable		U+1511: CANADIAN SYLLABICS SHI	
ᔒ		syllable		U+1512: CANADIAN SYLLABICS SHII	
ᔓ		syllable		U+1513: CANADIAN SYLLABICS SHO	
ᔔ		syllable		U+1514: CANADIAN SYLLABICS SHOO	
ᔕ		syllable		U+1515: CANADIAN SYLLABICS SHA	
ᔖ		syllable		U+1516: CANADIAN SYLLABICS SHAA	
ᔗ		syllable		U+1517: CANADIAN SYLLABICS SHWE	
ᔘ		syllable		U+1518: CANADIAN SYLLABICS WEST-CREE SHWE	
ᔙ		syllable		U+1519: CANADIAN SYLLABICS SHWI	
ᔚ		syllable		U+151A: CANADIAN SYLLABICS WEST-CREE SHWI	
ᔛ		syllable		U+151B: CANADIAN SYLLABICS SHWII	
ᔜ		syllable		U+151C: CANADIAN SYLLABICS WEST-CREE SHWII	
ᔝ		syllable		U+151D: CANADIAN SYLLABICS SHWO	
ᔞ		syllable		U+151E: CANADIAN SYLLABICS WEST-CREE SHWO	
ᔟ		syllable		U+151F: CANADIAN SYLLABICS SHWOO	
ᔠ		syllable		U+1520: CANADIAN SYLLABICS WEST-CREE SHWOO	
ᔡ		syllable		U+1521: CANADIAN SYLLABICS SHWA	
ᔢ		syllable		U+1522: CANADIAN SYLLABICS WEST-CREE SHWA	
ᔣ		syllable		U+1523: CANADIAN SYLLABICS SHWAA	
ᔤ		syllable		U+1524: CANADIAN SYLLABICS WEST-CREE SHWAA	
ᔥ		letter		U+1525: CANADIAN SYLLABICS SH	
ᔦ		syllable		U+1526: CANADIAN SYLLABICS YE	🗸
ᔧ		syllable		U+1527: CANADIAN SYLLABICS YAAI	
ᔨ		syllable		U+1528: CANADIAN SYLLABICS YI	🗸
ᔩ		syllable		U+1529: CANADIAN SYLLABICS YII	🗸
ᔪ		syllable		U+152A: CANADIAN SYLLABICS YO	🗸
ᔫ		syllable		U+152B: CANADIAN SYLLABICS YOO	🗸
ᔬ		syllable		U+152C: CANADIAN SYLLABICS Y-CREE YOO	
ᔭ		syllable		U+152D: CANADIAN SYLLABICS YA	🗸
ᔮ		syllable		U+152E: CANADIAN SYLLABICS YAA	🗸
ᔯ		syllable		U+152F: CANADIAN SYLLABICS YWE	
ᔰ		syllable		U+1530: CANADIAN SYLLABICS WEST-CREE YWE	🗸
ᔱ		syllable		U+1531: CANADIAN SYLLABICS YWI	
ᔲ		syllable		U+1532: CANADIAN SYLLABICS WEST-CREE YWI	🗸
ᔳ		syllable		U+1533: CANADIAN SYLLABICS YWII	
ᔴ		syllable		U+1534: CANADIAN SYLLABICS WEST-CREE YWII	🗸
ᔵ		syllable		U+1535: CANADIAN SYLLABICS YWO	
ᔶ		syllable		U+1536: CANADIAN SYLLABICS WEST-CREE YWO	🗸
ᔷ		syllable		U+1537: CANADIAN SYLLABICS YWOO	
ᔸ		syllable		U+1538: CANADIAN SYLLABICS WEST-CREE YWOO	🗸
ᔹ		syllable		U+1539: CANADIAN SYLLABICS YWA	
ᔺ		syllable		U+153A: CANADIAN SYLLABICS WEST-CREE YWA	🗸
ᔻ		syllable		U+153B: CANADIAN SYLLABICS YWAA	
ᔼ		syllable		U+153C: CANADIAN SYLLABICS WEST-CREE YWAA	🗸
ᔽ		syllable		U+153D: CANADIAN SYLLABICS NASKAPI YWAA	
ᔾ		letter		U+153E: CANADIAN SYLLABICS Y	🗸
ᔿ		syllable		U+153F: CANADIAN SYLLABICS BIBLE-CREE Y	
ᕀ		letter		U+1540: CANADIAN SYLLABICS WEST-CREE Y	🗸
ᕁ		syllable		U+1541: CANADIAN SYLLABICS SAYISI YI	
ᕂ		syllable		U+1542: CANADIAN SYLLABICS RE	
ᕃ		syllable		U+1543: CANADIAN SYLLABICS R-CREE RE	🗸
ᕄ		syllable		U+1544: CANADIAN SYLLABICS WEST-CREE LE	
ᕅ		syllable		U+1545: CANADIAN SYLLABICS RAAI	
ᕆ		syllable		U+1546: CANADIAN SYLLABICS RI	🗸
ᕇ		syllable		U+1547: CANADIAN SYLLABICS RII	🗸
ᕈ		syllable		U+1548: CANADIAN SYLLABICS RO	🗸
ᕉ		syllable		U+1549: CANADIAN SYLLABICS ROO	🗸
ᕊ		syllable		U+154A: CANADIAN SYLLABICS WEST-CREE LO	
ᕋ		syllable		U+154B: CANADIAN SYLLABICS RA	🗸
ᕌ		syllable		U+154C: CANADIAN SYLLABICS RAA	🗸
ᕍ		syllable		U+154D: CANADIAN SYLLABICS WEST-CREE LA	
ᕎ		syllable		U+154E: CANADIAN SYLLABICS RWAA	
ᕏ		syllable		U+154F: CANADIAN SYLLABICS WEST-CREE RWAA	
ᕐ		letter		U+1550: CANADIAN SYLLABICS R	🗸
ᕑ		syllable		U+1551: CANADIAN SYLLABICS WEST-CREE R	🗸
ᕒ		letter		U+1552: CANADIAN SYLLABICS MEDIAL R	🗸
ᕓ		syllable		U+1553: CANADIAN SYLLABICS FE	🗸
ᕔ		syllable		U+1554: CANADIAN SYLLABICS FAAI	
ᕕ		syllable		U+1555: CANADIAN SYLLABICS FI	🗸
ᕖ		syllable		U+1556: CANADIAN SYLLABICS FII	🗸
ᕗ		syllable		U+1557: CANADIAN SYLLABICS FO	🗸
ᕘ		syllable		U+1558: CANADIAN SYLLABICS FOO	🗸
ᕙ		syllable		U+1559: CANADIAN SYLLABICS FA	🗸
ᕚ		syllable		U+155A: CANADIAN SYLLABICS FAA	🗸
ᕛ		syllable		U+155B: CANADIAN SYLLABICS FWAA	
ᕜ		syllable		U+155C: CANADIAN SYLLABICS WEST-CREE FWAA	
ᕝ		letter		U+155D: CANADIAN SYLLABICS F	🗸
ᕞ		syllable		U+155E: CANADIAN SYLLABICS THE	
ᕟ		syllable		U+155F: CANADIAN SYLLABICS N-CREE THE	
ᕠ		syllable		U+1560: CANADIAN SYLLABICS THI	
ᕡ		syllable		U+1561: CANADIAN SYLLABICS N-CREE THI	
ᕢ		syllable		U+1562: CANADIAN SYLLABICS THII	
ᕣ		syllable		U+1563: CANADIAN SYLLABICS N-CREE THII	
ᕤ		syllable		U+1564: CANADIAN SYLLABICS THO	
ᕥ		syllable		U+1565: CANADIAN SYLLABICS THOO	
ᕦ		syllable		U+1566: CANADIAN SYLLABICS THA	
ᕧ		syllable		U+1567: CANADIAN SYLLABICS THAA	
ᕨ		syllable		U+1568: CANADIAN SYLLABICS THWAA	
ᕩ		syllable		U+1569: CANADIAN SYLLABICS WEST-CREE THWAA	
ᕪ		letter		U+156A: CANADIAN SYLLABICS TH	
ᕫ		syllable		U+156B: CANADIAN SYLLABICS TTHE	
ᕬ		syllable		U+156C: CANADIAN SYLLABICS TTHI	
ᕭ		syllable		U+156D: CANADIAN SYLLABICS TTHO	
ᕮ		syllable		U+156E: CANADIAN SYLLABICS TTHA	
ᕯ		syllable		U+156F: CANADIAN SYLLABICS TTH	
ᕰ		syllable		U+1570: CANADIAN SYLLABICS TYE	
ᕱ		syllable		U+1571: CANADIAN SYLLABICS TYI	
ᕲ		syllable		U+1572: CANADIAN SYLLABICS TYO	
ᕳ		syllable		U+1573: CANADIAN SYLLABICS TYA	
ᕴ		syllable		U+1574: CANADIAN SYLLABICS NUNAVIK HE	🗸
ᕵ		syllable		U+1575: CANADIAN SYLLABICS NUNAVIK HI	🗸
ᕶ		syllable		U+1576: CANADIAN SYLLABICS NUNAVIK HII	🗸
ᕷ		syllable		U+1577: CANADIAN SYLLABICS NUNAVIK HO	🗸
ᕸ		syllable		U+1578: CANADIAN SYLLABICS NUNAVIK HOO	🗸
ᕹ		syllable		U+1579: CANADIAN SYLLABICS NUNAVIK HA	🗸
ᕺ		syllable		U+157A: CANADIAN SYLLABICS NUNAVIK HAA	🗸
ᕻ		letter		U+157B: CANADIAN SYLLABICS NUNAVIK H	🗸
ᕼ		letter		U+157C: CANADIAN SYLLABICS NUNAVUT H	🗸
ᕽ		syllable		U+157D: CANADIAN SYLLABICS HK	🗸
ᕾ		syllable		U+157E: CANADIAN SYLLABICS QAAI	
ᕿ		syllable		U+157F: CANADIAN SYLLABICS QI	🗸
ᖀ		syllable		U+1580: CANADIAN SYLLABICS QII	🗸
ᖁ		syllable		U+1581: CANADIAN SYLLABICS QO	🗸
ᖂ		syllable		U+1582: CANADIAN SYLLABICS QOO	🗸
ᖃ		syllable		U+1583: CANADIAN SYLLABICS QA	🗸
ᖄ		syllable		U+1584: CANADIAN SYLLABICS QAA	🗸
ᖅ		syllable		U+1585: CANADIAN SYLLABICS Q	🗸
ᖆ		syllable		U+1586: CANADIAN SYLLABICS TLHE	
ᖇ		syllable		U+1587: CANADIAN SYLLABICS TLHI	
ᖈ		syllable		U+1588: CANADIAN SYLLABICS TLHO	
ᖉ		syllable		U+1589: CANADIAN SYLLABICS TLHA	
ᖊ		syllable		U+158A: CANADIAN SYLLABICS WEST-CREE RE	
ᖋ		syllable		U+158B: CANADIAN SYLLABICS WEST-CREE RI	
ᖌ		syllable		U+158C: CANADIAN SYLLABICS WEST-CREE RO	
ᖍ		syllable		U+158D: CANADIAN SYLLABICS WEST-CREE RA	
ᖎ		syllable		U+158E: CANADIAN SYLLABICS NGAAI	
ᖏ		syllable		U+158F: CANADIAN SYLLABICS NGI	🗸
ᖐ		syllable		U+1590: CANADIAN SYLLABICS NGII	🗸
ᖑ		syllable		U+1591: CANADIAN SYLLABICS NGO	🗸
ᖒ		syllable		U+1592: CANADIAN SYLLABICS NGOO	🗸
ᖓ		syllable		U+1593: CANADIAN SYLLABICS NGA	🗸
ᖔ		syllable		U+1594: CANADIAN SYLLABICS NGAA	🗸
ᖕ		syllable		U+1595: CANADIAN SYLLABICS NG	🗸
ᖖ		syllable		U+1596: CANADIAN SYLLABICS NNG	🗸
ᖗ		syllable		U+1597: CANADIAN SYLLABICS SAYISI SHE	
ᖘ		syllable		U+1598: CANADIAN SYLLABICS SAYISI SHI	
ᖙ		syllable		U+1599: CANADIAN SYLLABICS SAYISI SHO	
ᖚ		syllable		U+159A: CANADIAN SYLLABICS SAYISI SHA	
ᖛ		syllable		U+159B: CANADIAN SYLLABICS WOODS-CREE THE	
ᖜ		syllable		U+159C: CANADIAN SYLLABICS WOODS-CREE THI	
ᖝ		syllable		U+159D: CANADIAN SYLLABICS WOODS-CREE THO	
ᖞ		syllable		U+159E: CANADIAN SYLLABICS WOODS-CREE THA	
ᖟ		syllable		U+159F: CANADIAN SYLLABICS WOODS-CREE TH	
ᖠ		syllable		U+15A0: CANADIAN SYLLABICS LHI	🗸
ᖡ		syllable		U+15A1: CANADIAN SYLLABICS LHII	🗸
ᖢ		syllable		U+15A2: CANADIAN SYLLABICS LHO	🗸
ᖣ		syllable		U+15A3: CANADIAN SYLLABICS LHOO	🗸
ᖤ		syllable		U+15A4: CANADIAN SYLLABICS LHA	🗸
ᖥ		syllable		U+15A5: CANADIAN SYLLABICS LHAA	🗸
ᖦ		syllable		U+15A6: CANADIAN SYLLABICS LH	🗸
ᖧ		syllable		U+15A7: CANADIAN SYLLABICS TH-CREE THE	
ᖨ		syllable		U+15A8: CANADIAN SYLLABICS TH-CREE THI	
ᖩ		syllable		U+15A9: CANADIAN SYLLABICS TH-CREE THII	
ᖪ		syllable		U+15AA: CANADIAN SYLLABICS TH-CREE THO	
ᖫ		syllable		U+15AB: CANADIAN SYLLABICS TH-CREE THOO	
ᖬ		syllable		U+15AC: CANADIAN SYLLABICS TH-CREE THA	
ᖭ		syllable		U+15AD: CANADIAN SYLLABICS TH-CREE THAA	
ᖮ		letter		U+15AE: CANADIAN SYLLABICS TH-CREE TH	
ᖯ		letter		U+15AF: CANADIAN SYLLABICS AIVILIK B	🗸
ᖰ		syllable		U+15B0: CANADIAN SYLLABICS BLACKFOOT E	
ᖱ		syllable		U+15B1: CANADIAN SYLLABICS BLACKFOOT I	
ᖲ		syllable		U+15B2: CANADIAN SYLLABICS BLACKFOOT O	
ᖳ		syllable		U+15B3: CANADIAN SYLLABICS BLACKFOOT A	
ᖴ		syllable		U+15B4: CANADIAN SYLLABICS BLACKFOOT WE	
ᖵ		syllable		U+15B5: CANADIAN SYLLABICS BLACKFOOT WI	
ᖶ		syllable		U+15B6: CANADIAN SYLLABICS BLACKFOOT WO	
ᖷ		syllable		U+15B7: CANADIAN SYLLABICS BLACKFOOT WA	
ᖸ		syllable		U+15B8: CANADIAN SYLLABICS BLACKFOOT NE	
ᖹ		syllable		U+15B9: CANADIAN SYLLABICS BLACKFOOT NI	
ᖺ		syllable		U+15BA: CANADIAN SYLLABICS BLACKFOOT NO	
ᖻ		syllable		U+15BB: CANADIAN SYLLABICS BLACKFOOT NA	
ᖼ		syllable		U+15BC: CANADIAN SYLLABICS BLACKFOOT KE	
ᖽ		syllable		U+15BD: CANADIAN SYLLABICS BLACKFOOT KI	
ᖾ		syllable		U+15BE: CANADIAN SYLLABICS BLACKFOOT KO	
ᖿ		syllable		U+15BF: CANADIAN SYLLABICS BLACKFOOT KA	
ᗀ		syllable		U+15C0: CANADIAN SYLLABICS SAYISI HE	
ᗁ		syllable		U+15C1: CANADIAN SYLLABICS SAYISI HI	
ᗂ		syllable		U+15C2: CANADIAN SYLLABICS SAYISI HO	
ᗃ		syllable		U+15C3: CANADIAN SYLLABICS SAYISI HA	
ᗄ		syllable	Carrier	U+15C4: CANADIAN SYLLABICS CARRIER GHU	
ᗅ		syllable	Carrier	U+15C5: CANADIAN SYLLABICS CARRIER GHO	
ᗆ		syllable	Carrier	U+15C6: CANADIAN SYLLABICS CARRIER GHE	
ᗇ		syllable	Carrier	U+15C7: CANADIAN SYLLABICS CARRIER GHEE	
ᗈ		syllable	Carrier	U+15C8: CANADIAN SYLLABICS CARRIER GHI	
ᗉ		syllable	Carrier	U+15C9: CANADIAN SYLLABICS CARRIER GHA	
ᗊ		syllable	Carrier	U+15CA: CANADIAN SYLLABICS CARRIER RU	
ᗋ		syllable	Carrier	U+15CB: CANADIAN SYLLABICS CARRIER RO	
ᗌ		syllable	Carrier	U+15CC: CANADIAN SYLLABICS CARRIER RE	
ᗍ		syllable	Carrier	U+15CD: CANADIAN SYLLABICS CARRIER REE	
ᗎ		syllable	Carrier	U+15CE: CANADIAN SYLLABICS CARRIER RI	
ᗏ		syllable	Carrier	U+15CF: CANADIAN SYLLABICS CARRIER RA	
ᗐ		syllable	Carrier	U+15D0: CANADIAN SYLLABICS CARRIER WU	
ᗑ		syllable	Carrier	U+15D1: CANADIAN SYLLABICS CARRIER WO	
ᗒ		syllable	Carrier	U+15D2: CANADIAN SYLLABICS CARRIER WE	
ᗓ		syllable	Carrier	U+15D3: CANADIAN SYLLABICS CARRIER WEE	
ᗔ		syllable	Carrier	U+15D4: CANADIAN SYLLABICS CARRIER WI	
ᗕ		syllable	Carrier	U+15D5: CANADIAN SYLLABICS CARRIER WA	
ᗖ		syllable	Carrier	U+15D6: CANADIAN SYLLABICS CARRIER HWU	
ᗗ		syllable	Carrier	U+15D7: CANADIAN SYLLABICS CARRIER HWO	
ᗘ		syllable	Carrier	U+15D8: CANADIAN SYLLABICS CARRIER HWE	
ᗙ		syllable	Carrier	U+15D9: CANADIAN SYLLABICS CARRIER HWEE	
ᗚ		syllable	Carrier	U+15DA: CANADIAN SYLLABICS CARRIER HWI	
ᗛ		syllable	Carrier	U+15DB: CANADIAN SYLLABICS CARRIER HWA	
ᗜ		syllable	Carrier	U+15DC: CANADIAN SYLLABICS CARRIER THU	
ᗝ		syllable	Carrier	U+15DD: CANADIAN SYLLABICS CARRIER THO	
ᗞ		syllable	Carrier	U+15DE: CANADIAN SYLLABICS CARRIER THE	
ᗟ		syllable	Carrier	U+15DF: CANADIAN SYLLABICS CARRIER THEE	
ᗠ		syllable	Carrier	U+15E0: CANADIAN SYLLABICS CARRIER THI	
ᗡ		syllable	Carrier	U+15E1: CANADIAN SYLLABICS CARRIER THA	
ᗢ		syllable	Carrier	U+15E2: CANADIAN SYLLABICS CARRIER TTU	
ᗣ		syllable	Carrier	U+15E3: CANADIAN SYLLABICS CARRIER TTO	
ᗤ		syllable	Carrier	U+15E4: CANADIAN SYLLABICS CARRIER TTE	
ᗥ		syllable	Carrier	U+15E5: CANADIAN SYLLABICS CARRIER TTEE	
ᗦ		syllable	Carrier	U+15E6: CANADIAN SYLLABICS CARRIER TTI	
ᗧ		syllable	Carrier	U+15E7: CANADIAN SYLLABICS CARRIER TTA	
ᗨ		syllable	Carrier	U+15E8: CANADIAN SYLLABICS CARRIER PU	
ᗩ		syllable	Carrier	U+15E9: CANADIAN SYLLABICS CARRIER PO	
ᗪ		syllable	Carrier	U+15EA: CANADIAN SYLLABICS CARRIER PE	
ᗫ		syllable	Carrier	U+15EB: CANADIAN SYLLABICS CARRIER PEE	
ᗬ		syllable	Carrier	U+15EC: CANADIAN SYLLABICS CARRIER PI	
ᗭ		syllable	Carrier	U+15ED: CANADIAN SYLLABICS CARRIER PA	
ᗮ		letter	Carrier	U+15EE: CANADIAN SYLLABICS CARRIER P	
ᗯ		syllable	Carrier	U+15EF: CANADIAN SYLLABICS CARRIER GU	
ᗰ		syllable	Carrier	U+15F0: CANADIAN SYLLABICS CARRIER GO	
ᗱ		syllable	Carrier	U+15F1: CANADIAN SYLLABICS CARRIER GE	
ᗲ		syllable	Carrier	U+15F2: CANADIAN SYLLABICS CARRIER GEE	
ᗳ		syllable	Carrier	U+15F3: CANADIAN SYLLABICS CARRIER GI	
ᗴ		syllable	Carrier	U+15F4: CANADIAN SYLLABICS CARRIER GA	
ᗵ		syllable	Carrier	U+15F5: CANADIAN SYLLABICS CARRIER KHU	
ᗶ		syllable	Carrier	U+15F6: CANADIAN SYLLABICS CARRIER KHO	
ᗷ		syllable	Carrier	U+15F7: CANADIAN SYLLABICS CARRIER KHE	
ᗸ		syllable	Carrier	U+15F8: CANADIAN SYLLABICS CARRIER KHEE	
ᗹ		syllable	Carrier	U+15F9: CANADIAN SYLLABICS CARRIER KHI	
ᗺ		syllable	Carrier	U+15FA: CANADIAN SYLLABICS CARRIER KHA	
ᗻ		syllable	Carrier	U+15FB: CANADIAN SYLLABICS CARRIER KKU	
ᗼ		syllable	Carrier	U+15FC: CANADIAN SYLLABICS CARRIER KKO	
ᗽ		syllable	Carrier	U+15FD: CANADIAN SYLLABICS CARRIER KKE	
ᗾ		syllable	Carrier	U+15FE: CANADIAN SYLLABICS CARRIER KKEE	
ᗿ		syllable	Carrier	U+15FF: CANADIAN SYLLABICS CARRIER KKI	
ᘀ		syllable	Carrier	U+1600: CANADIAN SYLLABICS CARRIER KKA	
ᘁ		letter	Carrier	U+1601: CANADIAN SYLLABICS CARRIER KK	
ᘂ		syllable	Carrier	U+1602: CANADIAN SYLLABICS CARRIER NU	
ᘃ		syllable	Carrier	U+1603: CANADIAN SYLLABICS CARRIER NO	
ᘄ		syllable	Carrier	U+1604: CANADIAN SYLLABICS CARRIER NE	
ᘅ		syllable	Carrier	U+1605: CANADIAN SYLLABICS CARRIER NEE	
ᘆ		syllable	Carrier	U+1606: CANADIAN SYLLABICS CARRIER NI	
ᘇ		syllable	Carrier	U+1607: CANADIAN SYLLABICS CARRIER NA	
ᘈ		syllable	Carrier	U+1608: CANADIAN SYLLABICS CARRIER MU	
ᘉ		syllable	Carrier	U+1609: CANADIAN SYLLABICS CARRIER MO	
ᘊ		syllable	Carrier	U+160A: CANADIAN SYLLABICS CARRIER ME	
ᘋ		syllable	Carrier	U+160B: CANADIAN SYLLABICS CARRIER MEE	
ᘌ		syllable	Carrier	U+160C: CANADIAN SYLLABICS CARRIER MI	
ᘍ		syllable	Carrier	U+160D: CANADIAN SYLLABICS CARRIER MA	
ᘎ		syllable	Carrier	U+160E: CANADIAN SYLLABICS CARRIER YU	
ᘏ		syllable	Carrier	U+160F: CANADIAN SYLLABICS CARRIER YO	
ᘐ		syllable	Carrier	U+1610: CANADIAN SYLLABICS CARRIER YE	
ᘑ		syllable	Carrier	U+1611: CANADIAN SYLLABICS CARRIER YEE	
ᘒ		syllable	Carrier	U+1612: CANADIAN SYLLABICS CARRIER YI	
ᘓ		syllable	Carrier	U+1613: CANADIAN SYLLABICS CARRIER YA	
ᘔ		syllable	Carrier	U+1614: CANADIAN SYLLABICS CARRIER JU	
ᘕ		syllable	Carrier	U+1615: CANADIAN SYLLABICS SAYISI JU	
ᘖ		syllable	Carrier	U+1616: CANADIAN SYLLABICS CARRIER JO	
ᘗ		syllable	Carrier	U+1617: CANADIAN SYLLABICS CARRIER JE	
ᘘ		syllable	Carrier	U+1618: CANADIAN SYLLABICS CARRIER JEE	
ᘙ		syllable	Carrier	U+1619: CANADIAN SYLLABICS CARRIER JI	
ᘚ		syllable	Carrier	U+161A: CANADIAN SYLLABICS SAYISI JI	
ᘛ		syllable	Carrier	U+161B: CANADIAN SYLLABICS CARRIER JA	
ᘜ		syllable	Carrier	U+161C: CANADIAN SYLLABICS CARRIER JJU	
ᘝ		syllable	Carrier	U+161D: CANADIAN SYLLABICS CARRIER JJO	
ᘞ		syllable	Carrier	U+161E: CANADIAN SYLLABICS CARRIER JJE	
ᘟ		syllable	Carrier	U+161F: CANADIAN SYLLABICS CARRIER JJEE	
ᘠ		syllable	Carrier	U+1620: CANADIAN SYLLABICS CARRIER JJI	
ᘡ		syllable	Carrier	U+1621: CANADIAN SYLLABICS CARRIER JJA	
ᘢ		syllable	Carrier	U+1622: CANADIAN SYLLABICS CARRIER LU	
ᘣ		syllable	Carrier	U+1623: CANADIAN SYLLABICS CARRIER LO	
ᘤ		syllable	Carrier	U+1624: CANADIAN SYLLABICS CARRIER LE	
ᘥ		syllable	Carrier	U+1625: CANADIAN SYLLABICS CARRIER LEE	
ᘦ		syllable	Carrier	U+1626: CANADIAN SYLLABICS CARRIER LI	
ᘧ		syllable	Carrier	U+1627: CANADIAN SYLLABICS CARRIER LA	
ᘨ		syllable	Carrier	U+1628: CANADIAN SYLLABICS CARRIER DLU	
ᘩ		syllable	Carrier	U+1629: CANADIAN SYLLABICS CARRIER DLO	
ᘪ		syllable	Carrier	U+162A: CANADIAN SYLLABICS CARRIER DLE	
ᘫ		syllable	Carrier	U+162B: CANADIAN SYLLABICS CARRIER DLEE	
ᘬ		syllable	Carrier	U+162C: CANADIAN SYLLABICS CARRIER DLI	
ᘭ		syllable	Carrier	U+162D: CANADIAN SYLLABICS CARRIER DLA	
ᘮ		syllable	Carrier	U+162E: CANADIAN SYLLABICS CARRIER LHU	
ᘯ		syllable	Carrier	U+162F: CANADIAN SYLLABICS CARRIER LHO	
ᘰ		syllable	Carrier	U+1630: CANADIAN SYLLABICS CARRIER LHE	
ᘱ		syllable	Carrier	U+1631: CANADIAN SYLLABICS CARRIER LHEE	
ᘲ		syllable	Carrier	U+1632: CANADIAN SYLLABICS CARRIER LHI	
ᘳ		syllable	Carrier	U+1633: CANADIAN SYLLABICS CARRIER LHA	
ᘴ		syllable	Carrier	U+1634: CANADIAN SYLLABICS CARRIER TLHU	
ᘵ		syllable	Carrier	U+1635: CANADIAN SYLLABICS CARRIER TLHO	
ᘶ		syllable	Carrier	U+1636: CANADIAN SYLLABICS CARRIER TLHE	
ᘷ		syllable	Carrier	U+1637: CANADIAN SYLLABICS CARRIER TLHEE	
ᘸ		syllable	Carrier	U+1638: CANADIAN SYLLABICS CARRIER TLHI	
ᘹ		syllable	Carrier	U+1639: CANADIAN SYLLABICS CARRIER TLHA	
ᘺ		syllable	Carrier	U+163A: CANADIAN SYLLABICS CARRIER TLU	
ᘻ		syllable	Carrier	U+163B: CANADIAN SYLLABICS CARRIER TLO	
ᘼ		syllable	Carrier	U+163C: CANADIAN SYLLABICS CARRIER TLE	
ᘽ		syllable	Carrier	U+163D: CANADIAN SYLLABICS CARRIER TLEE	
ᘾ		syllable	Carrier	U+163E: CANADIAN SYLLABICS CARRIER TLI	
ᘿ		syllable	Carrier	U+163F: CANADIAN SYLLABICS CARRIER TLA	
ᙀ		syllable	Carrier	U+1640: CANADIAN SYLLABICS CARRIER ZU	
ᙁ		syllable	Carrier	U+1641: CANADIAN SYLLABICS CARRIER ZO	
ᙂ		syllable	Carrier	U+1642: CANADIAN SYLLABICS CARRIER ZE	
ᙃ		syllable	Carrier	U+1643: CANADIAN SYLLABICS CARRIER ZEE	
ᙄ		syllable	Carrier	U+1644: CANADIAN SYLLABICS CARRIER ZI	
ᙅ		syllable	Carrier	U+1645: CANADIAN SYLLABICS CARRIER ZA	
ᙆ		letter	Carrier	U+1646: CANADIAN SYLLABICS CARRIER Z	
ᙇ		initial z	Carrier	U+1647: CANADIAN SYLLABICS CARRIER INITIAL Z	
ᙈ		syllable	Carrier	U+1648: CANADIAN SYLLABICS CARRIER DZU	
ᙉ		syllable	Carrier	U+1649: CANADIAN SYLLABICS CARRIER DZO	
ᙊ		syllable	Carrier	U+164A: CANADIAN SYLLABICS CARRIER DZE	
ᙋ		syllable	Carrier	U+164B: CANADIAN SYLLABICS CARRIER DZEE	
ᙌ		syllable	Carrier	U+164C: CANADIAN SYLLABICS CARRIER DZI	
ᙍ		syllable	Carrier	U+164D: CANADIAN SYLLABICS CARRIER DZA	
ᙎ		syllable	Carrier	U+164E: CANADIAN SYLLABICS CARRIER SU	
ᙏ		syllable	Carrier	U+164F: CANADIAN SYLLABICS CARRIER SO	
ᙐ		syllable	Carrier	U+1650: CANADIAN SYLLABICS CARRIER SE	
ᙑ		syllable	Carrier	U+1651: CANADIAN SYLLABICS CARRIER SEE	
ᙒ		syllable	Carrier	U+1652: CANADIAN SYLLABICS CARRIER SI	
ᙓ		syllable	Carrier	U+1653: CANADIAN SYLLABICS CARRIER SA	
ᙔ		syllable	Carrier	U+1654: CANADIAN SYLLABICS CARRIER SHU	
ᙕ		syllable	Carrier	U+1655: CANADIAN SYLLABICS CARRIER SHO	
ᙖ		syllable	Carrier	U+1656: CANADIAN SYLLABICS CARRIER SHE	
ᙗ		syllable	Carrier	U+1657: CANADIAN SYLLABICS CARRIER SHEE	
ᙘ		syllable	Carrier	U+1658: CANADIAN SYLLABICS CARRIER SHI	
ᙙ		syllable	Carrier	U+1659: CANADIAN SYLLABICS CARRIER SHA	
ᙚ		letter	Carrier	U+165A: CANADIAN SYLLABICS CARRIER SH	
ᙛ		syllable	Carrier	U+165B: CANADIAN SYLLABICS CARRIER TSU	
ᙜ		syllable	Carrier	U+165C: CANADIAN SYLLABICS CARRIER TSO	
ᙝ		syllable	Carrier	U+165D: CANADIAN SYLLABICS CARRIER TSE	
ᙞ		syllable	Carrier	U+165E: CANADIAN SYLLABICS CARRIER TSEE	
ᙟ		syllable	Carrier	U+165F: CANADIAN SYLLABICS CARRIER TSI	
ᙠ		syllable	Carrier	U+1660: CANADIAN SYLLABICS CARRIER TSA	
ᙡ		syllable	Carrier	U+1661: CANADIAN SYLLABICS CARRIER CHU	
ᙢ		syllable	Carrier	U+1662: CANADIAN SYLLABICS CARRIER CHO	
ᙣ		syllable	Carrier	U+1663: CANADIAN SYLLABICS CARRIER CHE	
ᙤ		syllable	Carrier	U+1664: CANADIAN SYLLABICS CARRIER CHEE	
ᙥ		syllable	Carrier	U+1665: CANADIAN SYLLABICS CARRIER CHI	
ᙦ		syllable	Carrier	U+1666: CANADIAN SYLLABICS CARRIER CHA	
ᙧ		syllable	Carrier	U+1667: CANADIAN SYLLABICS CARRIER TTSU	
ᙨ		syllable	Carrier	U+1668: CANADIAN SYLLABICS CARRIER TTSO	
ᙩ		syllable	Carrier	U+1669: CANADIAN SYLLABICS CARRIER TTSE	
ᙪ		syllable	Carrier	U+166A: CANADIAN SYLLABICS CARRIER TTSEE	
ᙫ		syllable	Carrier	U+166B: CANADIAN SYLLABICS CARRIER TTSI	
ᙬ		syllable	Carrier	U+166C: CANADIAN SYLLABICS CARRIER TTSA	
᙭		symbol		U+166D: CANADIAN SYLLABICS CHI SIGN	
᙮		full stop punctuation		U+166E: CANADIAN SYLLABICS FULL STOP	🗸
ᙯ		syllable		U+166F: CANADIAN SYLLABICS QAI	🗸
ᙰ		syllable		U+1670: CANADIAN SYLLABICS NGAI	🗸
ᙱ		syllable		U+1671: CANADIAN SYLLABICS NNGI	🗸
ᙲ		syllable		U+1672: CANADIAN SYLLABICS NNGII	🗸
ᙳ		syllable		U+1673: CANADIAN SYLLABICS NNGO	🗸
ᙴ		syllable		U+1674: CANADIAN SYLLABICS NNGOO	🗸
ᙵ		syllable		U+1675: CANADIAN SYLLABICS NNGA	🗸
ᙶ		syllable		U+1676: CANADIAN SYLLABICS NNGAA	🗸
ᙷ		syllable		U+1677: CANADIAN SYLLABICS WOODS-CREE THWEE	
ᙸ		syllable		U+1678: CANADIAN SYLLABICS WOODS-CREE THWI	
ᙹ		syllable		U+1679: CANADIAN SYLLABICS WOODS-CREE THWII	
ᙺ		syllable		U+167A: CANADIAN SYLLABICS WOODS-CREE THWO	
ᙻ		syllable		U+167B: CANADIAN SYLLABICS WOODS-CREE THWOO	
ᙼ		syllable		U+167C: CANADIAN SYLLABICS WOODS-CREE THWA	
ᙽ		syllable		U+167D: CANADIAN SYLLABICS WOODS-CREE THWAA	
ᙾ		final letter		U+167E: CANADIAN SYLLABICS WOODS-CREE FINAL TH	
ᙿ		letter		U+167F: CANADIAN SYLLABICS BLACKFOOT W	
					
					
ᢰ		syllable	moose cree	U+18B0: CANADIAN SYLLABICS OY	
ᢱ		syllable	moose cree	U+18B1: CANADIAN SYLLABICS AY	
ᢲ		syllable	moose cree	U+18B2: CANADIAN SYLLABICS AAY	
ᢳ		syllable	moose cree	U+18B3: CANADIAN SYLLABICS WAY	
ᢴ		syllable	moose cree	U+18B4: CANADIAN SYLLABICS POY	
ᢵ		syllable	moose cree	U+18B5: CANADIAN SYLLABICS PAY	
ᢶ		syllable	moose cree	U+18B6: CANADIAN SYLLABICS PWOY	
ᢷ		syllable	moose cree	U+18B7: CANADIAN SYLLABICS TAY	
ᢸ		syllable	moose cree	U+18B8: CANADIAN SYLLABICS KAY	
ᢹ		syllable	moose cree	U+18B9: CANADIAN SYLLABICS KWAY	
ᢺ		syllable	moose cree	U+18BA: CANADIAN SYLLABICS MAY	
ᢻ		syllable	moose cree	U+18BB: CANADIAN SYLLABICS NOY	
ᢼ		syllable	moose cree	U+18BC: CANADIAN SYLLABICS NAY	
ᢽ		syllable	moose cree	U+18BD: CANADIAN SYLLABICS LAY	
ᢾ		syllable	moose cree	U+18BE: CANADIAN SYLLABICS SOY	
ᢿ		syllable	moose cree	U+18BF: CANADIAN SYLLABICS SAY	
ᣀ		syllable	moose cree	U+18C0: CANADIAN SYLLABICS SHOY	
ᣁ		syllable	moose cree	U+18C1: CANADIAN SYLLABICS SHAY	
ᣂ		syllable	moose cree	U+18C2: CANADIAN SYLLABICS SHWOY	
ᣃ		syllable	moose cree	U+18C3: CANADIAN SYLLABICS YOY	
ᣄ		syllable	moose cree	U+18C4: CANADIAN SYLLABICS YAY	
ᣅ		syllable	moose cree	U+18C5: CANADIAN SYLLABICS RAY	
ᣆ		syllable	cree & ojibwe	U+18C6: CANADIAN SYLLABICS NWI	
ᣇ		syllable	cree & ojibwe	U+18C7: CANADIAN SYLLABICS OJIBWAY NWI	🗸
ᣈ		syllable	cree & ojibwe	U+18C8: CANADIAN SYLLABICS NWII	
ᣉ		syllable	cree & ojibwe	U+18C9: CANADIAN SYLLABICS OJIBWAY NWII	🗸
ᣊ		syllable	cree & ojibwe	U+18CA: CANADIAN SYLLABICS NWO	
ᣋ		syllable	cree & ojibwe	U+18CB: CANADIAN SYLLABICS OJIBWAY NWO	🗸
ᣌ		syllable	cree & ojibwe	U+18CC: CANADIAN SYLLABICS NWOO	
ᣍ		syllable	cree & ojibwe	U+18CD: CANADIAN SYLLABICS OJIBWAY NWOO	🗸
ᣎ		syllable	cree & ojibwe	U+18CE: CANADIAN SYLLABICS RWEE	
ᣏ		syllable	cree & ojibwe	U+18CF: CANADIAN SYLLABICS RWI	
ᣐ		syllable	cree & ojibwe	U+18D0: CANADIAN SYLLABICS RWII	
ᣑ		syllable	cree & ojibwe	U+18D1: CANADIAN SYLLABICS RWO	
ᣒ		syllable	cree & ojibwe	U+18D2: CANADIAN SYLLABICS RWOO	
ᣓ		syllable	cree & ojibwe	U+18D3: CANADIAN SYLLABICS RWA	
ᣔ		final letter	cree & ojibwe	U+18D4: CANADIAN SYLLABICS OJIBWAY P	
ᣕ		final letter	cree & ojibwe	U+18D5: CANADIAN SYLLABICS OJIBWAY T	
ᣖ		final letter	cree & ojibwe	U+18D6: CANADIAN SYLLABICS OJIBWAY K	
ᣗ		final letter	cree & ojibwe	U+18D7: CANADIAN SYLLABICS OJIBWAY C	
ᣘ		final letter	cree & ojibwe	U+18D8: CANADIAN SYLLABICS OJIBWAY M	
ᣙ		final letter	cree & ojibwe	U+18D9: CANADIAN SYLLABICS OJIBWAY N	
ᣚ		final letter	cree & ojibwe	U+18DA: CANADIAN SYLLABICS OJIBWAY S	
ᣛ		final letter	cree & ojibwe	U+18DB: CANADIAN SYLLABICS OJIBWAY SH	
ᣜ		final letter	cree & ojibwe	U+18DC: CANADIAN SYLLABICS EASTERN W	
ᣝ		final letter	cree & ojibwe	U+18DD: CANADIAN SYLLABICS WESTERN W	
ᣞ		final letter	cree & ojibwe	U+18DE: CANADIAN SYLLABICS FINAL SMALL RING	🗸
ᣟ		final letter	cree & ojibwe	U+18DF: CANADIAN SYLLABICS FINAL RAISED DOT	🗸
ᣠ		syllable	beaver dene, hare dene & chipewyan dene	U+18E0: CANADIAN SYLLABICS R-CREE RWE	
ᣡ		syllable	beaver dene, hare dene & chipewyan dene	U+18E1: CANADIAN SYLLABICS WEST-CREE LOO	
ᣢ		syllable	beaver dene, hare dene & chipewyan dene	U+18E2: CANADIAN SYLLABICS WEST-CREE LAA	
ᣣ		syllable	beaver dene, hare dene & chipewyan dene	U+18E3: CANADIAN SYLLABICS THWE	
ᣤ		syllable	beaver dene, hare dene & chipewyan dene	U+18E4: CANADIAN SYLLABICS THWA	
ᣥ		syllable	beaver dene, hare dene & chipewyan dene	U+18E5: CANADIAN SYLLABICS TTHWE	
ᣦ		syllable	beaver dene, hare dene & chipewyan dene	U+18E6: CANADIAN SYLLABICS TTHOO	
ᣧ		syllable	beaver dene, hare dene & chipewyan dene	U+18E7: CANADIAN SYLLABICS TTHAA	
ᣨ		syllable	beaver dene, hare dene & chipewyan dene	U+18E8: CANADIAN SYLLABICS TLHWE	
ᣩ		syllable	beaver dene, hare dene & chipewyan dene	U+18E9: CANADIAN SYLLABICS TLHOO	
ᣪ		syllable	beaver dene, hare dene & chipewyan dene	U+18EA: CANADIAN SYLLABICS SAYISI SHWE	
ᣫ		syllable	beaver dene, hare dene & chipewyan dene	U+18EB: CANADIAN SYLLABICS SAYISI SHOO	
ᣬ		syllable	beaver dene, hare dene & chipewyan dene	U+18EC: CANADIAN SYLLABICS SAYISI HOO	
ᣭ		syllable	beaver dene, hare dene & chipewyan dene	U+18ED: CANADIAN SYLLABICS CARRIER GWU	
ᣮ		syllable	beaver dene, hare dene & chipewyan dene	U+18EE: CANADIAN SYLLABICS CARRIER DENE GEE	
ᣯ		syllable	beaver dene, hare dene & chipewyan dene	U+18EF: CANADIAN SYLLABICS CARRIER GAA	
ᣰ		syllable	beaver dene, hare dene & chipewyan dene	U+18F0: CANADIAN SYLLABICS CARRIER GWA	
ᣱ		syllable	beaver dene, hare dene & chipewyan dene	U+18F1: CANADIAN SYLLABICS SAYISI JUU	
ᣲ		syllable	beaver dene, hare dene & chipewyan dene	U+18F2: CANADIAN SYLLABICS CARRIER JWA	
ᣳ		final letter	dene & carrier	U+18F3: CANADIAN SYLLABICS BEAVER DENE L	
ᣴ		final letter	dene & carrier	U+18F4: CANADIAN SYLLABICS BEAVER DENE R	
ᣵ		final letter	dene & carrier	U+18F5: CANADIAN SYLLABICS CARRIER DENTAL S	
					
					
𑪰		syllable	Nattilik	U+11AB0: CANADIAN SYLLABICS NATTILIK HI	
𑪱		syllable	Nattilik	U+11AB1: CANADIAN SYLLABICS NATTILIK HII	
𑪲		syllable	Nattilik	U+11AB2: CANADIAN SYLLABICS NATTILIK HO	
𑪳		syllable	Nattilik	U+11AB3: CANADIAN SYLLABICS NATTILIK HOO	
𑪴		syllable	Nattilik	U+11AB4: CANADIAN SYLLABICS NATTILIK HA	
𑪵		syllable	Nattilik	U+11AB5: CANADIAN SYLLABICS NATTILIK HAA	
𑪶		syllable	Nattilik	U+11AB6: CANADIAN SYLLABICS NATTILIK SHRI	
𑪷		syllable	Nattilik	U+11AB7: CANADIAN SYLLABICS NATTILIK SHRII	
𑪸		syllable	Nattilik	U+11AB8: CANADIAN SYLLABICS NATTILIK SHRO	
𑪹		syllable	Nattilik	U+11AB9: CANADIAN SYLLABICS NATTILIK SHROO	
𑪺		syllable	Nattilik	U+11ABA: CANADIAN SYLLABICS NATTILIK SHRA	
𑪻		syllable	Nattilik	U+11ABB: CANADIAN SYLLABICS NATTILIK SHRAA	
𑪼		syllable	historic Cree & Ojibway	U+11ABC: CANADIAN SYLLABICS SPE	
𑪽		syllable	historic Cree & Ojibway	U+11ABD: CANADIAN SYLLABICS SPI	
𑪾		syllable	historic Cree & Ojibway	U+11ABE: CANADIAN SYLLABICS SPO	
𑪿		syllable	historic Cree & Ojibway	U+11ABF: CANADIAN SYLLABICS SPA	

												
\u202F		§	 								U+202F NARROW NO-BREAK SPACE	
\u2003		§	 								U+2003 EM SPACE	


`


var cols = {
"class": 1,
"key":0,
"transLoc": 0,
"ipaLoc": 0,
"transckey": 0,
"transcription":0,
"typeLoc": 2,
"statusLoc": 3,
"dvowel": 0,
"ivowel": 0,
"subj":0,
"ltone":0,
"htone":0,
"lc":0,
"uc":0,
"meaning":0,
"shape": 0,
"numLoc": 0,
"nameLoc": 0,
"nnameLoc": 0,
"ucsName": 4,
"block": 5,

//"othertranscriptions": [[5, 'Latin']]
}

