var spreadsheet = `
a			a		letter					U+0061: LATIN SMALL LETTER A
à			à		letter					U+00E0: LATIN SMALL LETTER A WITH GRAVE
ȁ			ȁ		letter					U+0201: LATIN SMALL LETTER A WITH DOUBLE GRAVE
á			á		letter					U+00E1: LATIN SMALL LETTER A WITH ACUTE
â			â		letter					U+00E2: LATIN SMALL LETTER A WITH CIRCUMFLEX
ǎ			ǎ		letter					U+01CE: LATIN SMALL LETTER A WITH CARON
ã			ã		letter					U+00E3: LATIN SMALL LETTER A WITH TILDE
ā			ā		letter					U+0101: LATIN SMALL LETTER A WITH MACRON
ă			ă		letter					U+0103: LATIN SMALL LETTER A WITH BREVE
ȃ			ȃ		letter					U+0203: LATIN SMALL LETTER A WITH INVERTED BREVE
ȧ			ȧ		letter					U+0227: LATIN SMALL LETTER A WITH DOT ABOVE
ä			ä		letter					U+00E4: LATIN SMALL LETTER A WITH DIAERESIS
å			å		letter					U+00E5: LATIN SMALL LETTER A WITH RING ABOVE
ẚ			ẚ		letter					U+1E9A: LATIN SMALL LETTER A WITH RIGHT HALF RING
ả			ả		letter					U+1EA3: LATIN SMALL LETTER A WITH HOOK ABOVE
ạ			ạ		letter					U+1EA1: LATIN SMALL LETTER A WITH DOT BELOW
ḁ			ḁ		letter					U+1E01: LATIN SMALL LETTER A WITH RING BELOW
ą			ą		letter					U+0105: LATIN SMALL LETTER A WITH OGONEK
ᶏ			ᶏ		letter					U+1D8F: LATIN SMALL LETTER A WITH RETROFLEX HOOK
ậ			ậ		letter					U+1EAD: LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
ặ			ặ		letter					U+1EB7: LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
ầ			ầ		letter					U+1EA7: LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
ằ			ằ		letter					U+1EB1: LATIN SMALL LETTER A WITH BREVE AND GRAVE
ắ			ắ		letter					U+1EAF: LATIN SMALL LETTER A WITH BREVE AND ACUTE
ấ			ấ		letter					U+1EA5: LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
ǻ			ǻ		letter					U+01FB: LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
ẫ			ẫ		letter					U+1EAB: LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
ẵ			ẵ		letter					U+1EB5: LATIN SMALL LETTER A WITH BREVE AND TILDE
ǡ			ǡ		letter					U+01E1: LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
ǟ			ǟ		letter					U+01DF: LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
ẩ			ẩ		letter					U+1EA9: LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
ẳ			ẳ		letter					U+1EB3: LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
ⱥ			ⱥ		letter					U+2C65: LATIN SMALL LETTER A WITH STROKE
æ			æ		letter					U+00E6: LATIN SMALL LETTER AE
ǽ			ǽ		letter					U+01FD: LATIN SMALL LETTER AE WITH ACUTE
ǣ			ǣ		letter					U+01E3: LATIN SMALL LETTER AE WITH MACRON
ᴂ			ᴂ		letter					U+1D02: LATIN SMALL LETTER TURNED AE
ꬱ			ꬱ		letter					U+AB31: LATIN SMALL LETTER A REVERSED-SCHWA
ꜳ			ꜳ		letter					U+A733: LATIN SMALL LETTER AA
ꜵ			ꜵ		letter					U+A735: LATIN SMALL LETTER AO
ꜷ			ꜷ		letter					U+A737: LATIN SMALL LETTER AU
ꜹ			ꜹ		letter					U+A739: LATIN SMALL LETTER AV
ꜻ			ꜻ		letter					U+A73B: LATIN SMALL LETTER AV WITH HORIZONTAL BAR
ꜽ			ꜽ		letter					U+A73D: LATIN SMALL LETTER AY
ɐ			ɐ		letter					U+0250: LATIN SMALL LETTER TURNED A
ɑ			ɑ		letter					U+0251: LATIN SMALL LETTER ALPHA
ꭤ			ꭤ		letter					U+AB64: LATIN SMALL LETTER INVERTED ALPHA
ᶐ			ᶐ		letter					U+1D90: LATIN SMALL LETTER ALPHA WITH RETROFLEX HOOK
ꬰ			ꬰ		letter					U+AB30: LATIN SMALL LETTER BARRED ALPHA
ɒ			ɒ		letter					U+0252: LATIN SMALL LETTER TURNED ALPHA
ᵃ			ᵃ		letter					U+1D43: MODIFIER LETTER SMALL A
ª			ª		letter					U+00AA: FEMININE ORDINAL INDICATOR
ᵄ			ᵄ		letter					U+1D44: MODIFIER LETTER SMALL TURNED A
ᵆ			ᵆ		letter					U+1D46: MODIFIER LETTER SMALL TURNED AE
ᵅ			ᵅ		letter					U+1D45: MODIFIER LETTER SMALL ALPHA
ᶛ			ᶛ		letter					U+1D9B: MODIFIER LETTER SMALL TURNED ALPHA
ᴬ			ᴬ		letter					U+1D2C: MODIFIER LETTER CAPITAL A
ᴭ			ᴭ		letter					U+1D2D: MODIFIER LETTER CAPITAL AE
ᴀ			ᴀ		letter					U+1D00: LATIN LETTER SMALL CAPITAL A
ᴁ			ᴁ		letter					U+1D01: LATIN LETTER SMALL CAPITAL AE
ₐ			ₐ		letter					U+2090: LATIN SUBSCRIPT SMALL LETTER A
b			b		letter					U+0062: LATIN SMALL LETTER B
ḃ			ḃ		letter					U+1E03: LATIN SMALL LETTER B WITH DOT ABOVE
ƅ			ƅ		letter					U+0185: LATIN SMALL LETTER TONE SIX
ƀ			ƀ		letter					U+0180: LATIN SMALL LETTER B WITH STROKE
ᵬ			ᵬ		letter					U+1D6C: LATIN SMALL LETTER B WITH MIDDLE TILDE
ɓ			ɓ		letter					U+0253: LATIN SMALL LETTER B WITH HOOK
ƃ			ƃ		letter					U+0183: LATIN SMALL LETTER B WITH TOPBAR
ḅ			ḅ		letter					U+1E05: LATIN SMALL LETTER B WITH DOT BELOW
ḇ			ḇ		letter					U+1E07: LATIN SMALL LETTER B WITH LINE BELOW
ᶀ			ᶀ		letter					U+1D80: LATIN SMALL LETTER B WITH PALATAL HOOK
ꞗ			ꞗ		letter					U+A797: LATIN SMALL LETTER B WITH FLOURISH
ȸ			ȸ		letter					U+0238: LATIN SMALL LETTER DB DIGRAPH
ß			ß		letter					U+00DF: LATIN SMALL LETTER SHARP S
ẞ			ẞ		letter					U+1E9E: LATIN CAPITAL LETTER SHARP S
ꞵ			ꞵ		letter					U+A7B5: LATIN SMALL LETTER BETA
ꞛ			ꞛ		letter					U+A79B: LATIN SMALL LETTER VOLAPUK AE
ꞝ			ꞝ		letter					U+A79D: LATIN SMALL LETTER VOLAPUK OE
ᵇ			ᵇ		letter					U+1D47: MODIFIER LETTER SMALL B
ᵝ			ᵝ		letter					U+1D5D: MODIFIER LETTER SMALL BETA
ᴮ			ᴮ		letter					U+1D2E: MODIFIER LETTER CAPITAL B
ᴯ			ᴯ		letter					U+1D2F: MODIFIER LETTER CAPITAL BARRED B
ʙ			ʙ		letter					U+0299: LATIN LETTER SMALL CAPITAL B
ᴃ			ᴃ		letter					U+1D03: LATIN LETTER SMALL CAPITAL BARRED B
ᵦ			ᵦ		letter					U+1D66: GREEK SUBSCRIPT SMALL LETTER BETA
c			c		letter					U+0063: LATIN SMALL LETTER C
ć			ć		letter					U+0107: LATIN SMALL LETTER C WITH ACUTE
ĉ			ĉ		letter					U+0109: LATIN SMALL LETTER C WITH CIRCUMFLEX
č			č		letter					U+010D: LATIN SMALL LETTER C WITH CARON
ċ			ċ		letter					U+010B: LATIN SMALL LETTER C WITH DOT ABOVE
ƈ			ƈ		letter					U+0188: LATIN SMALL LETTER C WITH HOOK
ç			ç		letter					U+00E7: LATIN SMALL LETTER C WITH CEDILLA
ḉ			ḉ		letter					U+1E09: LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
ɕ			ɕ		letter					U+0255: LATIN SMALL LETTER C WITH CURL
ꞔ			ꞔ		letter					U+A794: LATIN SMALL LETTER C WITH PALATAL HOOK
ꞓ			ꞓ		letter					U+A793: LATIN SMALL LETTER C WITH BAR
ȼ			ȼ		letter					U+023C: LATIN SMALL LETTER C WITH STROKE
ʗ			ʗ		letter					U+0297: LATIN LETTER STRETCHED C
ᴐ			ᴐ		letter					U+1D10: LATIN LETTER SMALL CAPITAL OPEN O
ᴒ			ᴒ		letter					U+1D12: LATIN SMALL LETTER SIDEWAYS OPEN O
ɔ			ɔ		letter					U+0254: LATIN SMALL LETTER OPEN O
ꜿ			ꜿ		letter					U+A73F: LATIN SMALL LETTER REVERSED C WITH DOT
ᶗ			ᶗ		letter					U+1D97: LATIN SMALL LETTER OPEN O WITH RETROFLEX HOOK
Ꝣ			Ꝣ		letter					U+A762: LATIN CAPITAL LETTER VISIGOTHIC Z
ꝣ			ꝣ		letter					U+A763: LATIN SMALL LETTER VISIGOTHIC Z
ᶜ			ᶜ		letter					U+1D9C: MODIFIER LETTER SMALL C
ᶝ			ᶝ		letter					U+1D9D: MODIFIER LETTER SMALL C WITH CURL
ᵓ			ᵓ		letter					U+1D53: MODIFIER LETTER SMALL OPEN O
ᴄ			ᴄ		letter					U+1D04: LATIN LETTER SMALL CAPITAL C
d			d		letter					U+0064: LATIN SMALL LETTER D
ď			ď		letter					U+010F: LATIN SMALL LETTER D WITH CARON
ḋ			ḋ		letter					U+1E0B: LATIN SMALL LETTER D WITH DOT ABOVE
ᵭ			ᵭ		letter					U+1D6D: LATIN SMALL LETTER D WITH MIDDLE TILDE
ð			ð		letter					U+00F0: LATIN SMALL LETTER ETH
đ			đ		letter					U+0111: LATIN SMALL LETTER D WITH STROKE
ɗ			ɗ		letter					U+0257: LATIN SMALL LETTER D WITH HOOK
ᶑ			ᶑ		letter					U+1D91: LATIN SMALL LETTER D WITH HOOK AND TAIL
ḓ			ḓ		letter					U+1E13: LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
ḍ			ḍ		letter					U+1E0D: LATIN SMALL LETTER D WITH DOT BELOW
ḏ			ḏ		letter					U+1E0F: LATIN SMALL LETTER D WITH LINE BELOW
ḑ			ḑ		letter					U+1E11: LATIN SMALL LETTER D WITH CEDILLA
ᶁ			ᶁ		letter					U+1D81: LATIN SMALL LETTER D WITH PALATAL HOOK
ɖ			ɖ		letter					U+0256: LATIN SMALL LETTER D WITH TAIL
ȡ			ȡ		letter					U+0221: LATIN SMALL LETTER D WITH CURL
ꝱ			ꝱ		letter					U+A771: LATIN SMALL LETTER DUM
ǳ			ǳ		letter					U+01F3: LATIN SMALL LETTER DZ
ʣ			ʣ		letter					U+02A3: LATIN SMALL LETTER DZ DIGRAPH
ǆ			ǆ		letter					U+01C6: LATIN SMALL LETTER DZ WITH CARON
ʤ			ʤ		letter					U+02A4: LATIN SMALL LETTER DEZH DIGRAPH
ʥ			ʥ		letter					U+02A5: LATIN SMALL LETTER DZ DIGRAPH WITH CURL
ȸ			ȸ		letter					U+0238: LATIN SMALL LETTER DB DIGRAPH
ǲ			ǲ		letter					U+01F2: LATIN CAPITAL LETTER D WITH SMALL LETTER Z
ǅ			ǅ		letter					U+01C5: LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
ꝺ			ꝺ		letter					U+A77A: LATIN SMALL LETTER INSULAR D
ẟ			ẟ		letter					U+1E9F: LATIN SMALL LETTER DELTA
ƍ			ƍ		letter					U+018D: LATIN SMALL LETTER TURNED DELTA
ƌ			ƌ		letter					U+018C: LATIN SMALL LETTER D WITH TOPBAR
ᵈ			ᵈ		letter					U+1D48: MODIFIER LETTER SMALL D
ᶞ			ᶞ		letter					U+1D9E: MODIFIER LETTER SMALL ETH
ᵟ			ᵟ		letter					U+1D5F: MODIFIER LETTER SMALL DELTA
ᴰ			ᴰ		letter					U+1D30: MODIFIER LETTER CAPITAL D
ᴅ			ᴅ		letter					U+1D05: LATIN LETTER SMALL CAPITAL D
ᴆ			ᴆ		letter					U+1D06: LATIN LETTER SMALL CAPITAL ETH
e			e		letter					U+0065: LATIN SMALL LETTER E
è			è		letter					U+00E8: LATIN SMALL LETTER E WITH GRAVE
ȅ			ȅ		letter					U+0205: LATIN SMALL LETTER E WITH DOUBLE GRAVE
é			é		letter					U+00E9: LATIN SMALL LETTER E WITH ACUTE
ē			ē		letter					U+0113: LATIN SMALL LETTER E WITH MACRON
ê			ê		letter					U+00EA: LATIN SMALL LETTER E WITH CIRCUMFLEX
ě			ě		letter					U+011B: LATIN SMALL LETTER E WITH CARON
ȇ			ȇ		letter					U+0207: LATIN SMALL LETTER E WITH INVERTED BREVE
ĕ			ĕ		letter					U+0115: LATIN SMALL LETTER E WITH BREVE
ẽ			ẽ		letter					U+1EBD: LATIN SMALL LETTER E WITH TILDE
ė			ė		letter					U+0117: LATIN SMALL LETTER E WITH DOT ABOVE
ë			ë		letter					U+00EB: LATIN SMALL LETTER E WITH DIAERESIS
ẻ			ẻ		letter					U+1EBB: LATIN SMALL LETTER E WITH HOOK ABOVE
ḙ			ḙ		letter					U+1E19: LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
ḛ			ḛ		letter					U+1E1B: LATIN SMALL LETTER E WITH TILDE BELOW
ẹ			ẹ		letter					U+1EB9: LATIN SMALL LETTER E WITH DOT BELOW
ȩ			ȩ		letter					U+0229: LATIN SMALL LETTER E WITH CEDILLA
ę			ę		letter					U+0119: LATIN SMALL LETTER E WITH OGONEK
ᶒ			ᶒ		letter					U+1D92: LATIN SMALL LETTER E WITH RETROFLEX HOOK
ⱸ			ⱸ		letter					U+2C78: LATIN SMALL LETTER E WITH NOTCH
ệ			ệ		letter					U+1EC7: LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
ḝ			ḝ		letter					U+1E1D: LATIN SMALL LETTER E WITH CEDILLA AND BREVE
ề			ề		letter					U+1EC1: LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
ḕ			ḕ		letter					U+1E15: LATIN SMALL LETTER E WITH MACRON AND GRAVE
ế			ế		letter					U+1EBF: LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
ḗ			ḗ		letter					U+1E17: LATIN SMALL LETTER E WITH MACRON AND ACUTE
ễ			ễ		letter					U+1EC5: LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
ể			ể		letter					U+1EC3: LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
ɇ			ɇ		letter					U+0247: LATIN SMALL LETTER E WITH STROKE
ə			ə		letter					U+0259: LATIN SMALL LETTER SCHWA
ǝ			ǝ		letter					U+01DD: LATIN SMALL LETTER TURNED E
ɘ			ɘ		letter					U+0258: LATIN SMALL LETTER REVERSED E
ɚ			ɚ		letter					U+025A: LATIN SMALL LETTER SCHWA WITH HOOK
ᶕ			ᶕ		letter					U+1D95: LATIN SMALL LETTER SCHWA WITH RETROFLEX HOOK
ꬲ			ꬲ		letter					U+AB32: LATIN SMALL LETTER BLACKLETTER E
ꬳ			ꬳ		letter					U+AB33: LATIN SMALL LETTER BARRED E
ꬴ			ꬴ		letter					U+AB34: LATIN SMALL LETTER E WITH FLOURISH
ᴔ			ᴔ		letter					U+1D14: LATIN SMALL LETTER TURNED OE
ꭁ			ꭁ		letter					U+AB41: LATIN SMALL LETTER TURNED OE WITH STROKE
ꭂ			ꭂ		letter					U+AB42: LATIN SMALL LETTER TURNED OE WITH HORIZONTAL STROKE
ꜫ			ꜫ		letter					U+A72B: LATIN SMALL LETTER TRESILLO
ɛ			ɛ		letter					U+025B: LATIN SMALL LETTER OPEN E
ᶓ			ᶓ		letter					U+1D93: LATIN SMALL LETTER OPEN E WITH RETROFLEX HOOK
ȝ			ȝ		letter					U+021D: LATIN SMALL LETTER YOGH
ꜣ			ꜣ		letter					U+A723: LATIN SMALL LETTER EGYPTOLOGICAL ALEF
ꝫ			ꝫ		letter					U+A76B: LATIN SMALL LETTER ET
ɜ			ɜ		letter					U+025C: LATIN SMALL LETTER REVERSED OPEN E
ᴈ			ᴈ		letter					U+1D08: LATIN SMALL LETTER TURNED OPEN E
ᶔ			ᶔ		letter					U+1D94: LATIN SMALL LETTER REVERSED OPEN E WITH RETROFLEX HOOK
ɝ			ɝ		letter					U+025D: LATIN SMALL LETTER REVERSED OPEN E WITH HOOK
ɞ			ɞ		letter					U+025E: LATIN SMALL LETTER CLOSED REVERSED OPEN E
Ʃ			Ʃ		letter					U+01A9: LATIN CAPITAL LETTER ESH
ᵉ			ᵉ		letter					U+1D49: MODIFIER LETTER SMALL E
ᵊ			ᵊ		letter					U+1D4A: MODIFIER LETTER SMALL SCHWA
ᵋ			ᵋ		letter					U+1D4B: MODIFIER LETTER SMALL OPEN E
ᵌ			ᵌ		letter					U+1D4C: MODIFIER LETTER SMALL TURNED OPEN E
ᶟ			ᶟ		letter					U+1D9F: MODIFIER LETTER SMALL REVERSED OPEN E
ᴱ			ᴱ		letter					U+1D31: MODIFIER LETTER CAPITAL E
ᴲ			ᴲ		letter					U+1D32: MODIFIER LETTER CAPITAL REVERSED E
ᴇ			ᴇ		letter					U+1D07: LATIN LETTER SMALL CAPITAL E
ⱻ			ⱻ		letter					U+2C7B: LATIN LETTER SMALL CAPITAL TURNED E
ₑ			ₑ		letter					U+2091: LATIN SUBSCRIPT SMALL LETTER E
ₔ			ₔ		letter					U+2094: LATIN SUBSCRIPT SMALL LETTER SCHWA
f			f		letter					U+0066: LATIN SMALL LETTER F
ẜ			ẜ		letter					U+1E9C: LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE
ẝ			ẝ		letter					U+1E9D: LATIN SMALL LETTER LONG S WITH HIGH STROKE
ƒ			ƒ		letter					U+0192: LATIN SMALL LETTER F WITH HOOK
ꬵ			ꬵ		letter					U+AB35: LATIN SMALL LETTER LENIS F
ḟ			ḟ		letter					U+1E1F: LATIN SMALL LETTER F WITH DOT ABOVE
ẛ			ẛ		letter					U+1E9B: LATIN SMALL LETTER LONG S WITH DOT ABOVE
ᶂ			ᶂ		letter					U+1D82: LATIN SMALL LETTER F WITH PALATAL HOOK
ᵮ			ᵮ		letter					U+1D6E: LATIN SMALL LETTER F WITH MIDDLE TILDE
ꞙ			ꞙ		letter					U+A799: LATIN SMALL LETTER F WITH STROKE
ꝭ			ꝭ		letter					U+A76D: LATIN SMALL LETTER IS
ꝼ			ꝼ		letter					U+A77C: LATIN SMALL LETTER INSULAR F
ʩ			ʩ		letter					U+02A9: LATIN SMALL LETTER FENG DIGRAPH
ꟻ			ꟻ		letter					U+A7FB: LATIN EPIGRAPHIC LETTER REVERSED F
ﬀ			ﬀ		letter					U+FB00: LATIN SMALL LIGATURE FF
ﬁ			ﬁ		letter					U+FB01: LATIN SMALL LIGATURE FI
ﬂ			ﬂ		letter					U+FB02: LATIN SMALL LIGATURE FL
ﬃ			ﬃ		letter					U+FB03: LATIN SMALL LIGATURE FFI
ﬄ			ﬄ		letter					U+FB04: LATIN SMALL LIGATURE FFL
ᶠ			ᶠ		letter					U+1DA0: MODIFIER LETTER SMALL F
ꜰ			ꜰ		letter					U+A730: LATIN LETTER SMALL CAPITAL F
g			g		letter					U+0067: LATIN SMALL LETTER G
ǵ			ǵ		letter					U+01F5: LATIN SMALL LETTER G WITH ACUTE
ḡ			ḡ		letter					U+1E21: LATIN SMALL LETTER G WITH MACRON
ĝ			ĝ		letter					U+011D: LATIN SMALL LETTER G WITH CIRCUMFLEX
ǧ			ǧ		letter					U+01E7: LATIN SMALL LETTER G WITH CARON
ğ			ğ		letter					U+011F: LATIN SMALL LETTER G WITH BREVE
ġ			ġ		letter					U+0121: LATIN SMALL LETTER G WITH DOT ABOVE
ģ			ģ		letter					U+0123: LATIN SMALL LETTER G WITH CEDILLA
ǥ			ǥ		letter					U+01E5: LATIN SMALL LETTER G WITH STROKE
ꬶ			ꬶ		letter					U+AB36: LATIN SMALL LETTER SCRIPT G WITH CROSSED-TAIL
ᵷ			ᵷ		letter					U+1D77: LATIN SMALL LETTER TURNED G
ɡ			ɡ		letter					U+0261: LATIN SMALL LETTER SCRIPT G
ᶃ			ᶃ		letter					U+1D83: LATIN SMALL LETTER G WITH PALATAL HOOK
ɠ			ɠ		letter					U+0260: LATIN SMALL LETTER G WITH HOOK
ꞡ			ꞡ		letter					U+A7A1: LATIN SMALL LETTER G WITH OBLIQUE STROKE
ᵍ			ᵍ		letter					U+1D4D: MODIFIER LETTER SMALL G
ᶢ			ᶢ		letter					U+1DA2: MODIFIER LETTER SMALL SCRIPT G
ᴳ			ᴳ		letter					U+1D33: MODIFIER LETTER CAPITAL G
ɢ			ɢ		letter					U+0262: LATIN LETTER SMALL CAPITAL G
ʛ			ʛ		letter					U+029B: LATIN LETTER SMALL CAPITAL G WITH HOOK
h			h		letter					U+0068: LATIN SMALL LETTER H
ħ			ħ		letter					U+0127: LATIN SMALL LETTER H WITH STROKE
ĥ			ĥ		letter					U+0125: LATIN SMALL LETTER H WITH CIRCUMFLEX
ȟ			ȟ		letter					U+021F: LATIN SMALL LETTER H WITH CARON
ḣ			ḣ		letter					U+1E23: LATIN SMALL LETTER H WITH DOT ABOVE
ḧ			ḧ		letter					U+1E27: LATIN SMALL LETTER H WITH DIAERESIS
ɦ			ɦ		letter					U+0266: LATIN SMALL LETTER H WITH HOOK
ɧ			ɧ		letter					U+0267: LATIN SMALL LETTER HENG WITH HOOK
ḫ			ḫ		letter					U+1E2B: LATIN SMALL LETTER H WITH BREVE BELOW
ḥ			ḥ		letter					U+1E25: LATIN SMALL LETTER H WITH DOT BELOW
ẖ			ẖ		letter					U+1E96: LATIN SMALL LETTER H WITH LINE BELOW
ḩ			ḩ		letter					U+1E29: LATIN SMALL LETTER H WITH CEDILLA
ⱨ			ⱨ		letter					U+2C68: LATIN SMALL LETTER H WITH DESCENDER
ꜧ			ꜧ		letter					U+A727: LATIN SMALL LETTER HENG
ꞕ			ꞕ		letter					U+A795: LATIN SMALL LETTER H WITH PALATAL HOOK
ƕ			ƕ		letter					U+0195: LATIN SMALL LETTER HV
ɥ			ɥ		letter					U+0265: LATIN SMALL LETTER TURNED H
ʮ			ʮ		letter					U+02AE: LATIN SMALL LETTER TURNED H WITH FISHHOOK
ʯ			ʯ		letter					U+02AF: LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL
ʰ			ʰ		letter					U+02B0: MODIFIER LETTER SMALL H
ʱ			ʱ		letter					U+02B1: MODIFIER LETTER SMALL H WITH HOOK
ꭜ			ꭜ		letter					U+AB5C: MODIFIER LETTER SMALL HENG
ᶣ			ᶣ		letter					U+1DA3: MODIFIER LETTER SMALL TURNED H
ᵸ			ᵸ		letter					U+1D78: MODIFIER LETTER CYRILLIC EN
ꟸ			ꟸ		letter					U+A7F8: MODIFIER LETTER CAPITAL H WITH STROKE
ᴴ			ᴴ		letter					U+1D34: MODIFIER LETTER CAPITAL H
ʜ			ʜ		letter					U+029C: LATIN LETTER SMALL CAPITAL H
ₕ			ₕ		letter					U+2095: LATIN SUBSCRIPT SMALL LETTER H
i			i		letter					U+0069: LATIN SMALL LETTER I
ì			ì		letter					U+00EC: LATIN SMALL LETTER I WITH GRAVE
ȉ			ȉ		letter					U+0209: LATIN SMALL LETTER I WITH DOUBLE GRAVE
í			í		letter					U+00ED: LATIN SMALL LETTER I WITH ACUTE
ī			ī		letter					U+012B: LATIN SMALL LETTER I WITH MACRON
ĩ			ĩ		letter					U+0129: LATIN SMALL LETTER I WITH TILDE
î			î		letter					U+00EE: LATIN SMALL LETTER I WITH CIRCUMFLEX
ǐ			ǐ		letter					U+01D0: LATIN SMALL LETTER I WITH CARON
ȋ			ȋ		letter					U+020B: LATIN SMALL LETTER I WITH INVERTED BREVE
ĭ			ĭ		letter					U+012D: LATIN SMALL LETTER I WITH BREVE
ï			ï		letter					U+00EF: LATIN SMALL LETTER I WITH DIAERESIS
ỉ			ỉ		letter					U+1EC9: LATIN SMALL LETTER I WITH HOOK ABOVE
ɨ			ɨ		letter					U+0268: LATIN SMALL LETTER I WITH STROKE
ḭ			ḭ		letter					U+1E2D: LATIN SMALL LETTER I WITH TILDE BELOW
ị			ị		letter					U+1ECB: LATIN SMALL LETTER I WITH DOT BELOW
į			į		letter					U+012F: LATIN SMALL LETTER I WITH OGONEK
ᶖ			ᶖ		letter					U+1D96: LATIN SMALL LETTER I WITH RETROFLEX HOOK
ḯ			ḯ		letter					U+1E2F: LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
ı			ı		letter					U+0131: LATIN SMALL LETTER DOTLESS I
ɩ			ɩ		letter					U+0269: LATIN SMALL LETTER IOTA
ɪ			ɪ		letter					U+026A: LATIN LETTER SMALL CAPITAL I
ꭠ			ꭠ		letter					U+AB60: LATIN SMALL LETTER SAKHA YAT
ꭡ			ꭡ		letter					U+AB61: LATIN SMALL LETTER IOTIFIED E
ᴉ			ᴉ		letter					U+1D09: LATIN SMALL LETTER TURNED I
ᵻ			ᵻ		letter					U+1D7B: LATIN SMALL CAPITAL LETTER I WITH STROKE
ᵼ			ᵼ		letter					U+1D7C: LATIN SMALL LETTER IOTA WITH STROKE
ĳ			ĳ		letter					U+0133: LATIN SMALL LIGATURE IJ
ỻ			ỻ		letter					U+1EFB: LATIN SMALL LETTER MIDDLE-WELSH LL
İ			İ		letter					U+0130: LATIN CAPITAL LETTER I WITH DOT ABOVE
ꟾ			ꟾ		letter					U+A7FE: LATIN EPIGRAPHIC LETTER I LONGA
ꟷ			ꟷ		letter					U+A7F7: LATIN EPIGRAPHIC LETTER SIDEWAYS I
ⁱ			ⁱ		letter					U+2071: SUPERSCRIPT LATIN SMALL LETTER I
ᶤ			ᶤ		letter					U+1DA4: MODIFIER LETTER SMALL I WITH STROKE
ᶦ			ᶦ		letter					U+1DA6: MODIFIER LETTER SMALL CAPITAL I
ᵎ			ᵎ		letter					U+1D4E: MODIFIER LETTER SMALL TURNED I
ᶧ			ᶧ		letter					U+1DA7: MODIFIER LETTER SMALL CAPITAL I WITH STROKE
ᶥ			ᶥ		letter					U+1DA5: MODIFIER LETTER SMALL IOTA
ᴵ			ᴵ		letter					U+1D35: MODIFIER LETTER CAPITAL I
ᵢ			ᵢ		letter					U+1D62: LATIN SUBSCRIPT SMALL LETTER I
j			j		letter					U+006A: LATIN SMALL LETTER J
ȷ			ȷ		letter					U+0237: LATIN SMALL LETTER DOTLESS J
ĵ			ĵ		letter					U+0135: LATIN SMALL LETTER J WITH CIRCUMFLEX
ǰ			ǰ		letter					U+01F0: LATIN SMALL LETTER J WITH CARON
ɉ			ɉ		letter					U+0249: LATIN SMALL LETTER J WITH STROKE
ɟ			ɟ		letter					U+025F: LATIN SMALL LETTER DOTLESS J WITH STROKE
ʝ			ʝ		letter					U+029D: LATIN SMALL LETTER J WITH CROSSED-TAIL
ĳ			ĳ		letter					U+0133: LATIN SMALL LIGATURE IJ
ʲ			ʲ		letter					U+02B2: MODIFIER LETTER SMALL J
ᶡ			ᶡ		letter					U+1DA1: MODIFIER LETTER SMALL DOTLESS J WITH STROKE
ᶨ			ᶨ		letter					U+1DA8: MODIFIER LETTER SMALL J WITH CROSSED-TAIL
ᴶ			ᴶ		letter					U+1D36: MODIFIER LETTER CAPITAL J
ᴊ			ᴊ		letter					U+1D0A: LATIN LETTER SMALL CAPITAL J
ⱼ			ⱼ		letter					U+2C7C: LATIN SUBSCRIPT SMALL LETTER J
k			k		letter					U+006B: LATIN SMALL LETTER K
ḱ			ḱ		letter					U+1E31: LATIN SMALL LETTER K WITH ACUTE
ǩ			ǩ		letter					U+01E9: LATIN SMALL LETTER K WITH CARON
ꝁ			ꝁ		letter					U+A741: LATIN SMALL LETTER K WITH STROKE
ꝃ			ꝃ		letter					U+A743: LATIN SMALL LETTER K WITH DIAGONAL STROKE
ꝅ			ꝅ		letter					U+A745: LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE
ƙ			ƙ		letter					U+0199: LATIN SMALL LETTER K WITH HOOK
ḳ			ḳ		letter					U+1E33: LATIN SMALL LETTER K WITH DOT BELOW
ḵ			ḵ		letter					U+1E35: LATIN SMALL LETTER K WITH LINE BELOW
ⱪ			ⱪ		letter					U+2C6A: LATIN SMALL LETTER K WITH DESCENDER
ķ			ķ		letter					U+0137: LATIN SMALL LETTER K WITH CEDILLA
ᶄ			ᶄ		letter					U+1D84: LATIN SMALL LETTER K WITH PALATAL HOOK
ꞣ			ꞣ		letter					U+A7A3: LATIN SMALL LETTER K WITH OBLIQUE STROKE
ʞ			ʞ		letter					U+029E: LATIN SMALL LETTER TURNED K
ĸ			ĸ		letter					U+0138: LATIN SMALL LETTER KRA
ᵏ			ᵏ		letter					U+1D4F: MODIFIER LETTER SMALL K
ᴷ			ᴷ		letter					U+1D37: MODIFIER LETTER CAPITAL K
ᴋ			ᴋ		letter					U+1D0B: LATIN LETTER SMALL CAPITAL K
ₖ			ₖ		letter					U+2096: LATIN SUBSCRIPT SMALL LETTER K
l			l		letter					U+006C: LATIN SMALL LETTER L
ĺ			ĺ		letter					U+013A: LATIN SMALL LETTER L WITH ACUTE
ľ			ľ		letter					U+013E: LATIN SMALL LETTER L WITH CARON
ŀ			ŀ		letter					U+0140: LATIN SMALL LETTER L WITH MIDDLE DOT
ł			ł		letter					U+0142: LATIN SMALL LETTER L WITH STROKE
ꝉ			ꝉ		letter					U+A749: LATIN SMALL LETTER L WITH HIGH STROKE
ƚ			ƚ		letter					U+019A: LATIN SMALL LETTER L WITH BAR
ⱡ			ⱡ		letter					U+2C61: LATIN SMALL LETTER L WITH DOUBLE BAR
ɫ			ɫ		letter					U+026B: LATIN SMALL LETTER L WITH MIDDLE TILDE
ꬷ			ꬷ		letter					U+AB37: LATIN SMALL LETTER L WITH INVERTED LAZY S
ꬸ			ꬸ		letter					U+AB38: LATIN SMALL LETTER L WITH DOUBLE MIDDLE TILDE
ɬ			ɬ		letter					U+026C: LATIN SMALL LETTER L WITH BELT
ꬹ			ꬹ		letter					U+AB39: LATIN SMALL LETTER L WITH MIDDLE RING
ḽ			ḽ		letter					U+1E3D: LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
ḷ			ḷ		letter					U+1E37: LATIN SMALL LETTER L WITH DOT BELOW
ḻ			ḻ		letter					U+1E3B: LATIN SMALL LETTER L WITH LINE BELOW
ļ			ļ		letter					U+013C: LATIN SMALL LETTER L WITH CEDILLA
ɭ			ɭ		letter					U+026D: LATIN SMALL LETTER L WITH RETROFLEX HOOK
ȴ			ȴ		letter					U+0234: LATIN SMALL LETTER L WITH CURL
ᶅ			ᶅ		letter					U+1D85: LATIN SMALL LETTER L WITH PALATAL HOOK
ꝲ			ꝲ		letter					U+A772: LATIN SMALL LETTER LUM
ḹ			ḹ		letter					U+1E39: LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
ꞎ			ꞎ		letter					U+A78E: LATIN SMALL LETTER L WITH RETROFLEX HOOK AND BELT
ꝇ			ꝇ		letter					U+A747: LATIN SMALL LETTER BROKEN L
ꞁ			ꞁ		letter					U+A781: LATIN SMALL LETTER TURNED L
ỻ			ỻ		letter					U+1EFB: LATIN SMALL LETTER MIDDLE-WELSH LL
ǈ			ǈ		letter					U+01C8: LATIN CAPITAL LETTER L WITH SMALL LETTER J
ǉ			ǉ		letter					U+01C9: LATIN SMALL LETTER LJ
ʪ			ʪ		letter					U+02AA: LATIN SMALL LETTER LS DIGRAPH
ʫ			ʫ		letter					U+02AB: LATIN SMALL LETTER LZ DIGRAPH
ɮ			ɮ		letter					U+026E: LATIN SMALL LETTER LEZH
ˡ			ˡ		letter					U+02E1: MODIFIER LETTER SMALL L
ᶩ			ᶩ		letter					U+1DA9: MODIFIER LETTER SMALL L WITH RETROFLEX HOOK
ᶪ			ᶪ		letter					U+1DAA: MODIFIER LETTER SMALL L WITH PALATAL HOOK
ꭝ			ꭝ		letter					U+AB5D: MODIFIER LETTER SMALL L WITH INVERTED LAZY S
ꭞ			ꭞ		letter					U+AB5E: MODIFIER LETTER SMALL L WITH MIDDLE TILDE
ᶫ			ᶫ		letter					U+1DAB: MODIFIER LETTER SMALL CAPITAL L
ᴸ			ᴸ		letter					U+1D38: MODIFIER LETTER CAPITAL L
ʟ			ʟ		letter					U+029F: LATIN LETTER SMALL CAPITAL L
ᴌ			ᴌ		letter					U+1D0C: LATIN LETTER SMALL CAPITAL L WITH STROKE
ₗ			ₗ		letter					U+2097: LATIN SUBSCRIPT SMALL LETTER L
m			m		letter					U+006D: LATIN SMALL LETTER M
ḿ			ḿ		letter					U+1E3F: LATIN SMALL LETTER M WITH ACUTE
ṁ			ṁ		letter					U+1E41: LATIN SMALL LETTER M WITH DOT ABOVE
ᵯ			ᵯ		letter					U+1D6F: LATIN SMALL LETTER M WITH MIDDLE TILDE
ṃ			ṃ		letter					U+1E43: LATIN SMALL LETTER M WITH DOT BELOW
ɱ			ɱ		letter					U+0271: LATIN SMALL LETTER M WITH HOOK
ᶆ			ᶆ		letter					U+1D86: LATIN SMALL LETTER M WITH PALATAL HOOK
ꝳ			ꝳ		letter					U+A773: LATIN SMALL LETTER MUM
ꬺ			ꬺ		letter					U+AB3A: LATIN SMALL LETTER M WITH CROSSED-TAIL
ꭑ			ꭑ		letter					U+AB51: LATIN SMALL LETTER TURNED UI
ᴟ			ᴟ		letter					U+1D1F: LATIN SMALL LETTER SIDEWAYS TURNED M
ɯ			ɯ		letter					U+026F: LATIN SMALL LETTER TURNED M
ɰ			ɰ		letter					U+0270: LATIN SMALL LETTER TURNED M WITH LONG LEG
ꟺ			ꟺ		letter					U+A7FA: LATIN LETTER SMALL CAPITAL TURNED M
ꟿ			ꟿ		letter					U+A7FF: LATIN EPIGRAPHIC LETTER ARCHAIC M
ꟽ			ꟽ		letter					U+A7FD: LATIN EPIGRAPHIC LETTER INVERTED M
ᵐ			ᵐ		letter					U+1D50: MODIFIER LETTER SMALL M
ᶬ			ᶬ		letter					U+1DAC: MODIFIER LETTER SMALL M WITH HOOK
ᶭ			ᶭ		letter					U+1DAD: MODIFIER LETTER SMALL TURNED M WITH LONG LEG
ᴹ			ᴹ		letter					U+1D39: MODIFIER LETTER CAPITAL M
ᴍ			ᴍ		letter					U+1D0D: LATIN LETTER SMALL CAPITAL M
ₘ			ₘ		letter					U+2098: LATIN SUBSCRIPT SMALL LETTER M
n			n		letter					U+006E: LATIN SMALL LETTER N
ǹ			ǹ		letter					U+01F9: LATIN SMALL LETTER N WITH GRAVE
ń			ń		letter					U+0144: LATIN SMALL LETTER N WITH ACUTE
ñ			ñ		letter					U+00F1: LATIN SMALL LETTER N WITH TILDE
ň			ň		letter					U+0148: LATIN SMALL LETTER N WITH CARON
ŉ			ŉ		letter					U+0149: LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
ṅ			ṅ		letter					U+1E45: LATIN SMALL LETTER N WITH DOT ABOVE
ᵰ			ᵰ		letter					U+1D70: LATIN SMALL LETTER N WITH MIDDLE TILDE
ṇ			ṇ		letter					U+1E47: LATIN SMALL LETTER N WITH DOT BELOW
ṉ			ṉ		letter					U+1E49: LATIN SMALL LETTER N WITH LINE BELOW
ṋ			ṋ		letter					U+1E4B: LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
ņ			ņ		letter					U+0146: LATIN SMALL LETTER N WITH CEDILLA
ŋ			ŋ		letter					U+014B: LATIN SMALL LETTER ENG
ɳ			ɳ		letter					U+0273: LATIN SMALL LETTER N WITH RETROFLEX HOOK
ɲ			ɲ		letter					U+0272: LATIN SMALL LETTER N WITH LEFT HOOK
ƞ			ƞ		letter					U+019E: LATIN SMALL LETTER N WITH LONG RIGHT LEG
ꬻ			ꬻ		letter					U+AB3B: LATIN SMALL LETTER N WITH CROSSED-TAIL
ꬼ			ꬼ		letter					U+AB3C: LATIN SMALL LETTER ENG WITH CROSSED-TAIL
ȵ			ȵ		letter					U+0235: LATIN SMALL LETTER N WITH CURL
ᶇ			ᶇ		letter					U+1D87: LATIN SMALL LETTER N WITH PALATAL HOOK
ꝴ			ꝴ		letter					U+A774: LATIN SMALL LETTER NUM
ꞃ			ꞃ		letter					U+A783: LATIN SMALL LETTER INSULAR R
ꞑ			ꞑ		letter					U+A791: LATIN SMALL LETTER N WITH DESCENDER
ꞥ			ꞥ		letter					U+A7A5: LATIN SMALL LETTER N WITH OBLIQUE STROKE
ᴝ			ᴝ		letter					U+1D1D: LATIN SMALL LETTER SIDEWAYS U
ᴞ			ᴞ		letter					U+1D1E: LATIN SMALL LETTER SIDEWAYS DIAERESIZED U
ǋ			ǋ		letter					U+01CB: LATIN CAPITAL LETTER N WITH SMALL LETTER J
ǌ			ǌ		letter					U+01CC: LATIN SMALL LETTER NJ
ⁿ			ⁿ		letter					U+207F: SUPERSCRIPT LATIN SMALL LETTER N
ᵑ			ᵑ		letter					U+1D51: MODIFIER LETTER SMALL ENG
ᶯ			ᶯ		letter					U+1DAF: MODIFIER LETTER SMALL N WITH RETROFLEX HOOK
ᶮ			ᶮ		letter					U+1DAE: MODIFIER LETTER SMALL N WITH LEFT HOOK
ᶰ			ᶰ		letter					U+1DB0: MODIFIER LETTER SMALL CAPITAL N
ᴺ			ᴺ		letter					U+1D3A: MODIFIER LETTER CAPITAL N
ᴻ			ᴻ		letter					U+1D3B: MODIFIER LETTER CAPITAL REVERSED N
ɴ			ɴ		letter					U+0274: LATIN LETTER SMALL CAPITAL N
ᴎ			ᴎ		letter					U+1D0E: LATIN LETTER SMALL CAPITAL REVERSED N
ₙ			ₙ		letter					U+2099: LATIN SUBSCRIPT SMALL LETTER N
o			o		letter					U+006F: LATIN SMALL LETTER O
ᴏ			ᴏ		letter					U+1D0F: LATIN LETTER SMALL CAPITAL O
ᴑ			ᴑ		letter					U+1D11: LATIN SMALL LETTER SIDEWAYS O
ò			ò		letter					U+00F2: LATIN SMALL LETTER O WITH GRAVE
ȍ			ȍ		letter					U+020D: LATIN SMALL LETTER O WITH DOUBLE GRAVE
ó			ó		letter					U+00F3: LATIN SMALL LETTER O WITH ACUTE
ǿ			ǿ		letter					U+01FF: LATIN SMALL LETTER O WITH STROKE AND ACUTE
ő			ő		letter					U+0151: LATIN SMALL LETTER O WITH DOUBLE ACUTE
ō			ō		letter					U+014D: LATIN SMALL LETTER O WITH MACRON
õ			õ		letter					U+00F5: LATIN SMALL LETTER O WITH TILDE
ô			ô		letter					U+00F4: LATIN SMALL LETTER O WITH CIRCUMFLEX
ȏ			ȏ		letter					U+020F: LATIN SMALL LETTER O WITH INVERTED BREVE
ǒ			ǒ		letter					U+01D2: LATIN SMALL LETTER O WITH CARON
ŏ			ŏ		letter					U+014F: LATIN SMALL LETTER O WITH BREVE
ȯ			ȯ		letter					U+022F: LATIN SMALL LETTER O WITH DOT ABOVE
ö			ö		letter					U+00F6: LATIN SMALL LETTER O WITH DIAERESIS
ỏ			ỏ		letter					U+1ECF: LATIN SMALL LETTER O WITH HOOK ABOVE
ơ			ơ		letter					U+01A1: LATIN SMALL LETTER O WITH HORN
ꝍ			ꝍ		letter					U+A74D: LATIN SMALL LETTER O WITH LOOP
ọ			ọ		letter					U+1ECD: LATIN SMALL LETTER O WITH DOT BELOW
ǫ			ǫ		letter					U+01EB: LATIN SMALL LETTER O WITH OGONEK
ⱺ			ⱺ		letter					U+2C7A: LATIN SMALL LETTER O WITH LOW RING INSIDE
ꝋ			ꝋ		letter					U+A74B: LATIN SMALL LETTER O WITH LONG STROKE OVERLAY
ɵ			ɵ		letter					U+0275: LATIN SMALL LETTER BARRED O
ø			ø		letter					U+00F8: LATIN SMALL LETTER O WITH STROKE
ᴓ			ᴓ		letter					U+1D13: LATIN SMALL LETTER SIDEWAYS O WITH STROKE
ǭ			ǭ		letter					U+01ED: LATIN SMALL LETTER O WITH OGONEK AND MACRON
ộ			ộ		letter					U+1ED9: LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
ợ			ợ		letter					U+1EE3: LATIN SMALL LETTER O WITH HORN AND DOT BELOW
ồ			ồ		letter					U+1ED3: LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
ṑ			ṑ		letter					U+1E51: LATIN SMALL LETTER O WITH MACRON AND GRAVE
ờ			ờ		letter					U+1EDD: LATIN SMALL LETTER O WITH HORN AND GRAVE
ố			ố		letter					U+1ED1: LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
ṍ			ṍ		letter					U+1E4D: LATIN SMALL LETTER O WITH TILDE AND ACUTE
ṓ			ṓ		letter					U+1E53: LATIN SMALL LETTER O WITH MACRON AND ACUTE
ớ			ớ		letter					U+1EDB: LATIN SMALL LETTER O WITH HORN AND ACUTE
ỗ			ỗ		letter					U+1ED7: LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
ỡ			ỡ		letter					U+1EE1: LATIN SMALL LETTER O WITH HORN AND TILDE
ṏ			ṏ		letter					U+1E4F: LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
ȭ			ȭ		letter					U+022D: LATIN SMALL LETTER O WITH TILDE AND MACRON
ȱ			ȱ		letter					U+0231: LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
ȫ			ȫ		letter					U+022B: LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
ổ			ổ		letter					U+1ED5: LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
ở			ở		letter					U+1EDF: LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
œ			œ		letter					U+0153: LATIN SMALL LIGATURE OE
ɶ			ɶ		letter					U+0276: LATIN LETTER SMALL CAPITAL OE
ƣ			ƣ		letter					U+01A3: LATIN SMALL LETTER OI
ɸ			ɸ		letter					U+0278: LATIN SMALL LETTER PHI
ƍ			ƍ		letter					U+018D: LATIN SMALL LETTER TURNED DELTA
ꝏ			ꝏ		letter					U+A74F: LATIN SMALL LETTER OO
ʘ			ʘ		letter					U+0298: LATIN LETTER BILABIAL CLICK
ꬽ			ꬽ		letter					U+AB3D: LATIN SMALL LETTER BLACKLETTER O
ꬾ			ꬾ		letter					U+AB3E: LATIN SMALL LETTER BLACKLETTER O WITH STROKE
ꬿ			ꬿ		letter					U+AB3F: LATIN SMALL LETTER OPEN O WITH STROKE
ꭀ			ꭀ		letter					U+AB40: LATIN SMALL LETTER INVERTED OE
ꭁ			ꭁ		letter					U+AB41: LATIN SMALL LETTER TURNED OE WITH STROKE
ꭂ			ꭂ		letter					U+AB42: LATIN SMALL LETTER TURNED OE WITH HORIZONTAL STROKE
ꭃ			ꭃ		letter					U+AB43: LATIN SMALL LETTER TURNED O OPEN-O
ꭄ			ꭄ		letter					U+AB44: LATIN SMALL LETTER TURNED O OPEN-O WITH STROKE
ꭢ			ꭢ		letter					U+AB62: LATIN SMALL LETTER OPEN OE
ꭣ			ꭣ		letter					U+AB63: LATIN SMALL LETTER UO
ᵒ			ᵒ		letter					U+1D52: MODIFIER LETTER SMALL O
ᶱ			ᶱ		letter					U+1DB1: MODIFIER LETTER SMALL BARRED O
º			º		letter					U+00BA: MASCULINE ORDINAL INDICATOR
ꟹ			ꟹ		letter					U+A7F9: MODIFIER LETTER SMALL LIGATURE OE
ᶲ			ᶲ		letter					U+1DB2: MODIFIER LETTER SMALL PHI
ᴼ			ᴼ		letter					U+1D3C: MODIFIER LETTER CAPITAL O
ᴽ			ᴽ		letter					U+1D3D: MODIFIER LETTER CAPITAL OU
ₒ			ₒ		letter					U+2092: LATIN SUBSCRIPT SMALL LETTER O
p			p		letter					U+0070: LATIN SMALL LETTER P
ṕ			ṕ		letter					U+1E55: LATIN SMALL LETTER P WITH ACUTE
ṗ			ṗ		letter					U+1E57: LATIN SMALL LETTER P WITH DOT ABOVE
ꝕ			ꝕ		letter					U+A755: LATIN SMALL LETTER P WITH SQUIRREL TAIL
ꝓ			ꝓ		letter					U+A753: LATIN SMALL LETTER P WITH FLOURISH
ᵽ			ᵽ		letter					U+1D7D: LATIN SMALL LETTER P WITH STROKE
ᵱ			ᵱ		letter					U+1D71: LATIN SMALL LETTER P WITH MIDDLE TILDE
ᶈ			ᶈ		letter					U+1D88: LATIN SMALL LETTER P WITH PALATAL HOOK
ꝑ			ꝑ		letter					U+A751: LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER
þ			þ		letter					U+00FE: LATIN SMALL LETTER THORN
ꝥ			ꝥ		letter					U+A765: LATIN SMALL LETTER THORN WITH STROKE
ꝧ			ꝧ		letter					U+A767: LATIN SMALL LETTER THORN WITH STROKE THROUGH DESCENDER
ƥ			ƥ		letter					U+01A5: LATIN SMALL LETTER P WITH HOOK
ƪ			ƪ		letter					U+01AA: LATIN LETTER REVERSED ESH LOOP
ƿ			ƿ		letter					U+01BF: LATIN LETTER WYNN
ȹ			ȹ		letter					U+0239: LATIN SMALL LETTER QP DIGRAPH
ꟼ			ꟼ		letter					U+A7FC: LATIN EPIGRAPHIC LETTER REVERSED P
ᵖ			ᵖ		letter					U+1D56: MODIFIER LETTER SMALL P
ᴾ			ᴾ		letter					U+1D3E: MODIFIER LETTER CAPITAL P
ᴘ			ᴘ		letter					U+1D18: LATIN LETTER SMALL CAPITAL P
ᴩ			ᴩ		letter					U+1D29: GREEK LETTER SMALL CAPITAL RHO
ᵨ			ᵨ		letter					U+1D68: GREEK SUBSCRIPT SMALL LETTER RHO
ₚ			ₚ		letter					U+209A: LATIN SUBSCRIPT SMALL LETTER P
q			q		letter					U+0071: LATIN SMALL LETTER Q
ʠ			ʠ		letter					U+02A0: LATIN SMALL LETTER Q WITH HOOK
ɋ			ɋ		letter					U+024B: LATIN SMALL LETTER Q WITH HOOK TAIL
ꝙ			ꝙ		letter					U+A759: LATIN SMALL LETTER Q WITH DIAGONAL STROKE
ꝗ			ꝗ		letter					U+A757: LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER
ȹ			ȹ		letter					U+0239: LATIN SMALL LETTER QP DIGRAPH
ꞯ			ꞯ		letter					U+A7AF: LATIN LETTER SMALL CAPITAL Q
ʘ			ʘ		letter					U+0298: LATIN LETTER BILABIAL CLICK
θ			θ		letter					U+03B8: GREEK SMALL LETTER THETA
ᶿ			ᶿ		letter					U+1DBF: MODIFIER LETTER SMALL THETA
r			r		letter					U+0072: LATIN SMALL LETTER R
ŕ			ŕ		letter					U+0155: LATIN SMALL LETTER R WITH ACUTE
ȑ			ȑ		letter					U+0211: LATIN SMALL LETTER R WITH DOUBLE GRAVE
ř			ř		letter					U+0159: LATIN SMALL LETTER R WITH CARON
ȓ			ȓ		letter					U+0213: LATIN SMALL LETTER R WITH INVERTED BREVE
ṙ			ṙ		letter					U+1E59: LATIN SMALL LETTER R WITH DOT ABOVE
ɍ			ɍ		letter					U+024D: LATIN SMALL LETTER R WITH STROKE
ᵲ			ᵲ		letter					U+1D72: LATIN SMALL LETTER R WITH MIDDLE TILDE
ꝵ			ꝵ		letter					U+A775: LATIN SMALL LETTER RUM
ꞧ			ꞧ		letter					U+A7A7: LATIN SMALL LETTER R WITH OBLIQUE STROKE
ṛ			ṛ		letter					U+1E5B: LATIN SMALL LETTER R WITH DOT BELOW
ŗ			ŗ		letter					U+0157: LATIN SMALL LETTER R WITH CEDILLA
ṟ			ṟ		letter					U+1E5F: LATIN SMALL LETTER R WITH LINE BELOW
ᶉ			ᶉ		letter					U+1D89: LATIN SMALL LETTER R WITH PALATAL HOOK
ꞅ			ꞅ		letter					U+A785: LATIN SMALL LETTER INSULAR S
ɼ			ɼ		letter					U+027C: LATIN SMALL LETTER R WITH LONG LEG
ɽ			ɽ		letter					U+027D: LATIN SMALL LETTER R WITH TAIL
ṝ			ṝ		letter					U+1E5D: LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
ɾ			ɾ		letter					U+027E: LATIN SMALL LETTER R WITH FISHHOOK
ᵳ			ᵳ		letter					U+1D73: LATIN SMALL LETTER R WITH FISHHOOK AND MIDDLE TILDE
ᴦ			ᴦ		letter					U+1D26: GREEK LETTER SMALL CAPITAL GAMMA
ɿ			ɿ		letter					U+027F: LATIN SMALL LETTER REVERSED R WITH FISHHOOK
ſ			ſ		letter					U+017F: LATIN SMALL LETTER LONG S
ⱹ			ⱹ		letter					U+2C79: LATIN SMALL LETTER TURNED R WITH TAIL
ɹ			ɹ		letter					U+0279: LATIN SMALL LETTER TURNED R
ɺ			ɺ		letter					U+027A: LATIN SMALL LETTER TURNED R WITH LONG LEG
ɻ			ɻ		letter					U+027B: LATIN SMALL LETTER TURNED R WITH HOOK
ꝶ			ꝶ		letter					U+A776: LATIN LETTER SMALL CAPITAL RUM
ꭇ			ꭇ		letter					U+AB47: LATIN SMALL LETTER R WITHOUT HANDLE
ꭈ			ꭈ		letter					U+AB48: LATIN SMALL LETTER DOUBLE R
ꭉ			ꭉ		letter					U+AB49: LATIN SMALL LETTER R WITH CROSSED-TAIL
ꭊ			ꭊ		letter					U+AB4A: LATIN SMALL LETTER DOUBLE R WITH CROSSED-TAIL
ꭋ			ꭋ		letter					U+AB4B: LATIN SMALL LETTER SCRIPT R
ꭌ			ꭌ		letter					U+AB4C: LATIN SMALL LETTER SCRIPT R WITH RING
ʳ			ʳ		letter					U+02B3: MODIFIER LETTER SMALL R
ʶ			ʶ		letter					U+02B6: MODIFIER LETTER SMALL CAPITAL INVERTED R
ʴ			ʴ		letter					U+02B4: MODIFIER LETTER SMALL TURNED R
ʵ			ʵ		letter					U+02B5: MODIFIER LETTER SMALL TURNED R WITH HOOK
ᴿ			ᴿ		letter					U+1D3F: MODIFIER LETTER CAPITAL R
ʀ			ʀ		letter					U+0280: LATIN LETTER SMALL CAPITAL R
ʁ			ʁ		letter					U+0281: LATIN LETTER SMALL CAPITAL INVERTED R
ᴙ			ᴙ		letter					U+1D19: LATIN LETTER SMALL CAPITAL REVERSED R
ᴚ			ᴚ		letter					U+1D1A: LATIN LETTER SMALL CAPITAL TURNED R
ꭆ			ꭆ		letter					U+AB46: LATIN LETTER SMALL CAPITAL R WITH RIGHT LEG
ᵣ			ᵣ		letter					U+1D63: LATIN SUBSCRIPT SMALL LETTER R
s			s		letter					U+0073: LATIN SMALL LETTER S
ś			ś		letter					U+015B: LATIN SMALL LETTER S WITH ACUTE
ŝ			ŝ		letter					U+015D: LATIN SMALL LETTER S WITH CIRCUMFLEX
š			š		letter					U+0161: LATIN SMALL LETTER S WITH CARON
ṡ			ṡ		letter					U+1E61: LATIN SMALL LETTER S WITH DOT ABOVE
ᵴ			ᵴ		letter					U+1D74: LATIN SMALL LETTER S WITH MIDDLE TILDE
ꞩ			ꞩ		letter					U+A7A9: LATIN SMALL LETTER S WITH OBLIQUE STROKE
ṣ			ṣ		letter					U+1E63: LATIN SMALL LETTER S WITH DOT BELOW
ş			ş		letter					U+015F: LATIN SMALL LETTER S WITH CEDILLA
ș			ș		letter					U+0219: LATIN SMALL LETTER S WITH COMMA BELOW
ȿ			ȿ		letter					U+023F: LATIN SMALL LETTER S WITH SWASH TAIL
ʂ			ʂ		letter					U+0282: LATIN SMALL LETTER S WITH HOOK
ᶊ			ᶊ		letter					U+1D8A: LATIN SMALL LETTER S WITH PALATAL HOOK
ṩ			ṩ		letter					U+1E69: LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
ṥ			ṥ		letter					U+1E65: LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
ṧ			ṧ		letter					U+1E67: LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
ƨ			ƨ		letter					U+01A8: LATIN SMALL LETTER TONE TWO
ʃ			ʃ		letter					U+0283: LATIN SMALL LETTER ESH
ʄ			ʄ		letter					U+0284: LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK
ʆ			ʆ		letter					U+0286: LATIN SMALL LETTER ESH WITH CURL
ᶋ			ᶋ		letter					U+1D8B: LATIN SMALL LETTER ESH WITH PALATAL HOOK
ᶘ			ᶘ		letter					U+1D98: LATIN SMALL LETTER ESH WITH RETROFLEX HOOK
ꭍ			ꭍ		letter					U+AB4D: LATIN SMALL LETTER BASELINE ESH
ʅ			ʅ		letter					U+0285: LATIN SMALL LETTER SQUAT REVERSED ESH
ƪ			ƪ		letter					U+01AA: LATIN LETTER REVERSED ESH LOOP
ﬅ			ﬅ		letter					U+FB05: LATIN SMALL LIGATURE LONG S T
ﬆ			ﬆ		letter					U+FB06: LATIN SMALL LIGATURE ST
ˢ			ˢ		letter					U+02E2: MODIFIER LETTER SMALL S
ᶳ			ᶳ		letter					U+1DB3: MODIFIER LETTER SMALL S WITH HOOK
ᶴ			ᶴ		letter					U+1DB4: MODIFIER LETTER SMALL ESH
ꜱ			ꜱ		letter					U+A731: LATIN LETTER SMALL CAPITAL S
ₛ			ₛ		letter					U+209B: LATIN SUBSCRIPT SMALL LETTER S
t			t		letter					U+0074: LATIN SMALL LETTER T
ť			ť		letter					U+0165: LATIN SMALL LETTER T WITH CARON
ṫ			ṫ		letter					U+1E6B: LATIN SMALL LETTER T WITH DOT ABOVE
ẗ			ẗ		letter					U+1E97: LATIN SMALL LETTER T WITH DIAERESIS
ƭ			ƭ		letter					U+01AD: LATIN SMALL LETTER T WITH HOOK
ⱦ			ⱦ		letter					U+2C66: LATIN SMALL LETTER T WITH DIAGONAL STROKE
ᵵ			ᵵ		letter					U+1D75: LATIN SMALL LETTER T WITH MIDDLE TILDE
ŧ			ŧ		letter					U+0167: LATIN SMALL LETTER T WITH STROKE
ꝷ			ꝷ		letter					U+A777: LATIN SMALL LETTER TUM
ṱ			ṱ		letter					U+1E71: LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
ṯ			ṯ		letter					U+1E6F: LATIN SMALL LETTER T WITH LINE BELOW
ṭ			ṭ		letter					U+1E6D: LATIN SMALL LETTER T WITH DOT BELOW
ţ			ţ		letter					U+0163: LATIN SMALL LETTER T WITH CEDILLA
ƫ			ƫ		letter					U+01AB: LATIN SMALL LETTER T WITH PALATAL HOOK
ʈ			ʈ		letter					U+0288: LATIN SMALL LETTER T WITH RETROFLEX HOOK
ț			ț		letter					U+021B: LATIN SMALL LETTER T WITH COMMA BELOW
ȶ			ȶ		letter					U+0236: LATIN SMALL LETTER T WITH CURL
ʇ			ʇ		letter					U+0287: LATIN SMALL LETTER TURNED T
ꞇ			ꞇ		letter					U+A787: LATIN SMALL LETTER INSULAR T
ꜩ			ꜩ		letter					U+A729: LATIN SMALL LETTER TZ
ʦ			ʦ		letter					U+02A6: LATIN SMALL LETTER TS DIGRAPH
ʧ			ʧ		letter					U+02A7: LATIN SMALL LETTER TESH DIGRAPH
ʨ			ʨ		letter					U+02A8: LATIN SMALL LETTER TC DIGRAPH WITH CURL
ᵺ			ᵺ		letter					U+1D7A: LATIN SMALL LETTER TH WITH STRIKETHROUGH
ᵗ			ᵗ		letter					U+1D57: MODIFIER LETTER SMALL T
ᶵ			ᶵ		letter					U+1DB5: MODIFIER LETTER SMALL T WITH PALATAL HOOK
ᵀ			ᵀ		letter					U+1D40: MODIFIER LETTER CAPITAL T
ᴛ			ᴛ		letter					U+1D1B: LATIN LETTER SMALL CAPITAL T
ₜ			ₜ		letter					U+209C: LATIN SUBSCRIPT SMALL LETTER T
u			u		letter					U+0075: LATIN SMALL LETTER U
ù			ù		letter					U+00F9: LATIN SMALL LETTER U WITH GRAVE
ȕ			ȕ		letter					U+0215: LATIN SMALL LETTER U WITH DOUBLE GRAVE
ú			ú		letter					U+00FA: LATIN SMALL LETTER U WITH ACUTE
ű			ű		letter					U+0171: LATIN SMALL LETTER U WITH DOUBLE ACUTE
ū			ū		letter					U+016B: LATIN SMALL LETTER U WITH MACRON
ũ			ũ		letter					U+0169: LATIN SMALL LETTER U WITH TILDE
û			û		letter					U+00FB: LATIN SMALL LETTER U WITH CIRCUMFLEX
ǔ			ǔ		letter					U+01D4: LATIN SMALL LETTER U WITH CARON
ȗ			ȗ		letter					U+0217: LATIN SMALL LETTER U WITH INVERTED BREVE
ŭ			ŭ		letter					U+016D: LATIN SMALL LETTER U WITH BREVE
ü			ü		letter					U+00FC: LATIN SMALL LETTER U WITH DIAERESIS
ů			ů		letter					U+016F: LATIN SMALL LETTER U WITH RING ABOVE
ủ			ủ		letter					U+1EE7: LATIN SMALL LETTER U WITH HOOK ABOVE
ư			ư		letter					U+01B0: LATIN SMALL LETTER U WITH HORN
ꭒ			ꭒ		letter					U+AB52: LATIN SMALL LETTER U WITH LEFT HOOK
ʉ			ʉ		letter					U+0289: LATIN SMALL LETTER U BAR
ꞹ			ꞹ		letter					U+A7B9: LATIN SMALL LETTER U WITH STROKE
ṷ			ṷ		letter					U+1E77: LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
ṵ			ṵ		letter					U+1E75: LATIN SMALL LETTER U WITH TILDE BELOW
ụ			ụ		letter					U+1EE5: LATIN SMALL LETTER U WITH DOT BELOW
ṳ			ṳ		letter					U+1E73: LATIN SMALL LETTER U WITH DIAERESIS BELOW
ų			ų		letter					U+0173: LATIN SMALL LETTER U WITH OGONEK
ᶙ			ᶙ		letter					U+1D99: LATIN SMALL LETTER U WITH RETROFLEX HOOK
ɥ			ɥ		letter					U+0265: LATIN SMALL LETTER TURNED H
ự			ự		letter					U+1EF1: LATIN SMALL LETTER U WITH HORN AND DOT BELOW
ǜ			ǜ		letter					U+01DC: LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
ừ			ừ		letter					U+1EEB: LATIN SMALL LETTER U WITH HORN AND GRAVE
ṹ			ṹ		letter					U+1E79: LATIN SMALL LETTER U WITH TILDE AND ACUTE
ǘ			ǘ		letter					U+01D8: LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
ứ			ứ		letter					U+1EE9: LATIN SMALL LETTER U WITH HORN AND ACUTE
ǚ			ǚ		letter					U+01DA: LATIN SMALL LETTER U WITH DIAERESIS AND CARON
ữ			ữ		letter					U+1EEF: LATIN SMALL LETTER U WITH HORN AND TILDE
ṻ			ṻ		letter					U+1E7B: LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
ǖ			ǖ		letter					U+01D6: LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
ử			ử		letter					U+1EED: LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
ʊ			ʊ		letter					U+028A: LATIN SMALL LETTER UPSILON
ᵫ			ᵫ		letter					U+1D6B: LATIN SMALL LETTER UE
ᵿ			ᵿ		letter					U+1D7F: LATIN SMALL LETTER UPSILON WITH STROKE
ꭎ			ꭎ		letter					U+AB4E: LATIN SMALL LETTER U WITH SHORT RIGHT LEG
ꭏ			ꭏ		letter					U+AB4F: LATIN SMALL LETTER U BAR WITH SHORT RIGHT LEG
ꭐ			ꭐ		letter					U+AB50: LATIN SMALL LETTER UI
ꭑ			ꭑ		letter					U+AB51: LATIN SMALL LETTER TURNED UI
ᵘ			ᵘ		letter					U+1D58: MODIFIER LETTER SMALL U
ᶶ			ᶶ		letter					U+1DB6: MODIFIER LETTER SMALL U BAR
ᶷ			ᶷ		letter					U+1DB7: MODIFIER LETTER SMALL UPSILON
ᵙ			ᵙ		letter					U+1D59: MODIFIER LETTER SMALL SIDEWAYS U
ᶸ			ᶸ		letter					U+1DB8: MODIFIER LETTER SMALL CAPITAL U
ꭟ			ꭟ		letter					U+AB5F: MODIFIER LETTER SMALL U WITH LEFT HOOK
ᵁ			ᵁ		letter					U+1D41: MODIFIER LETTER CAPITAL U
ᴜ			ᴜ		letter					U+1D1C: LATIN LETTER SMALL CAPITAL U
ᵾ			ᵾ		letter					U+1D7E: LATIN SMALL CAPITAL LETTER U WITH STROKE
ᵤ			ᵤ		letter					U+1D64: LATIN SUBSCRIPT SMALL LETTER U
v			v		letter					U+0076: LATIN SMALL LETTER V
ṽ			ṽ		letter					U+1E7D: LATIN SMALL LETTER V WITH TILDE
ⱱ			ⱱ		letter					U+2C71: LATIN SMALL LETTER V WITH RIGHT HOOK
ⱴ			ⱴ		letter					U+2C74: LATIN SMALL LETTER V WITH CURL
ꝟ			ꝟ		letter					U+A75F: LATIN SMALL LETTER V WITH DIAGONAL STROKE
ṿ			ṿ		letter					U+1E7F: LATIN SMALL LETTER V WITH DOT BELOW
ᶌ			ᶌ		letter					U+1D8C: LATIN SMALL LETTER V WITH PALATAL HOOK
ʋ			ʋ		letter					U+028B: LATIN SMALL LETTER V WITH HOOK
ʌ			ʌ		letter					U+028C: LATIN SMALL LETTER TURNED V
ᵛ			ᵛ		letter					U+1D5B: MODIFIER LETTER SMALL V
ⱽ			ⱽ		letter					U+2C7D: MODIFIER LETTER CAPITAL V
ᶹ			ᶹ		letter					U+1DB9: MODIFIER LETTER SMALL V WITH HOOK
ᶺ			ᶺ		letter					U+1DBA: MODIFIER LETTER SMALL TURNED V
ᴠ			ᴠ		letter					U+1D20: LATIN LETTER SMALL CAPITAL V
ᵥ			ᵥ		letter					U+1D65: LATIN SUBSCRIPT SMALL LETTER V
w			w		letter					U+0077: LATIN SMALL LETTER W
ẁ			ẁ		letter					U+1E81: LATIN SMALL LETTER W WITH GRAVE
ẃ			ẃ		letter					U+1E83: LATIN SMALL LETTER W WITH ACUTE
ŵ			ŵ		letter					U+0175: LATIN SMALL LETTER W WITH CIRCUMFLEX
ẇ			ẇ		letter					U+1E87: LATIN SMALL LETTER W WITH DOT ABOVE
ẅ			ẅ		letter					U+1E85: LATIN SMALL LETTER W WITH DIAERESIS
ẘ			ẘ		letter					U+1E98: LATIN SMALL LETTER W WITH RING ABOVE
ⱳ			ⱳ		letter					U+2C73: LATIN SMALL LETTER W WITH HOOK
ẉ			ẉ		letter					U+1E89: LATIN SMALL LETTER W WITH DOT BELOW
ꝡ			ꝡ		letter					U+A761: LATIN SMALL LETTER VY
ɯ			ɯ		letter					U+026F: LATIN SMALL LETTER TURNED M
ɰ			ɰ		letter					U+0270: LATIN SMALL LETTER TURNED M WITH LONG LEG
ꟽ			ꟽ		letter					U+A7FD: LATIN EPIGRAPHIC LETTER INVERTED M
ꟿ			ꟿ		letter					U+A7FF: LATIN EPIGRAPHIC LETTER ARCHAIC M
ʍ			ʍ		letter					U+028D: LATIN SMALL LETTER TURNED W
ʬ			ʬ		letter					U+02AC: LATIN LETTER BILABIAL PERCUSSIVE
Ꞷ			Ꞷ		letter					U+A7B6: LATIN CAPITAL LETTER OMEGA
ꞷ			ꞷ		letter					U+A7B7: LATIN SMALL LETTER OMEGA
ʷ			ʷ		letter					U+02B7: MODIFIER LETTER SMALL W
ᵚ			ᵚ		letter					U+1D5A: MODIFIER LETTER SMALL TURNED M
ᶭ			ᶭ		letter					U+1DAD: MODIFIER LETTER SMALL TURNED M WITH LONG LEG
ᵂ			ᵂ		letter					U+1D42: MODIFIER LETTER CAPITAL W
ᴡ			ᴡ		letter					U+1D21: LATIN LETTER SMALL CAPITAL W
x			x		letter					U+0078: LATIN SMALL LETTER X
ẋ			ẋ		letter					U+1E8B: LATIN SMALL LETTER X WITH DOT ABOVE
ẍ			ẍ		letter					U+1E8D: LATIN SMALL LETTER X WITH DIAERESIS
ᶍ			ᶍ		letter					U+1D8D: LATIN SMALL LETTER X WITH PALATAL HOOK
ꭓ			ꭓ		letter					U+AB53: LATIN SMALL LETTER CHI
ꭔ			ꭔ		letter					U+AB54: LATIN SMALL LETTER CHI WITH LOW RIGHT RING
ꭕ			ꭕ		letter					U+AB55: LATIN SMALL LETTER CHI WITH LOW LEFT SERIF
ꭖ			ꭖ		letter					U+AB56: LATIN SMALL LETTER X WITH LOW RIGHT RING
ꭗ			ꭗ		letter					U+AB57: LATIN SMALL LETTER X WITH LONG LEFT LEG
ꭘ			ꭘ		letter					U+AB58: LATIN SMALL LETTER X WITH LONG LEFT LEG AND LOW RIGHT RING
ꭙ			ꭙ		letter					U+AB59: LATIN SMALL LETTER X WITH LONG LEFT LEG WITH SERIF
ˣ			ˣ		letter					U+02E3: MODIFIER LETTER SMALL X
ᵡ			ᵡ		letter					U+1D61: MODIFIER LETTER SMALL CHI
ₓ			ₓ		letter					U+2093: LATIN SUBSCRIPT SMALL LETTER X
ᵪ			ᵪ		letter					U+1D6A: GREEK SUBSCRIPT SMALL LETTER CHI
y			y		letter					U+0079: LATIN SMALL LETTER Y
ỳ			ỳ		letter					U+1EF3: LATIN SMALL LETTER Y WITH GRAVE
ý			ý		letter					U+00FD: LATIN SMALL LETTER Y WITH ACUTE
ȳ			ȳ		letter					U+0233: LATIN SMALL LETTER Y WITH MACRON
ỹ			ỹ		letter					U+1EF9: LATIN SMALL LETTER Y WITH TILDE
ŷ			ŷ		letter					U+0177: LATIN SMALL LETTER Y WITH CIRCUMFLEX
ẏ			ẏ		letter					U+1E8F: LATIN SMALL LETTER Y WITH DOT ABOVE
ÿ			ÿ		letter					U+00FF: LATIN SMALL LETTER Y WITH DIAERESIS
ẙ			ẙ		letter					U+1E99: LATIN SMALL LETTER Y WITH RING ABOVE
ỷ			ỷ		letter					U+1EF7: LATIN SMALL LETTER Y WITH HOOK ABOVE
ƴ			ƴ		letter					U+01B4: LATIN SMALL LETTER Y WITH HOOK
ɏ			ɏ		letter					U+024F: LATIN SMALL LETTER Y WITH STROKE
ꭚ			ꭚ		letter					U+AB5A: LATIN SMALL LETTER Y WITH SHORT RIGHT LEG
ỵ			ỵ		letter					U+1EF5: LATIN SMALL LETTER Y WITH DOT BELOW
ỿ			ỿ		letter					U+1EFF: LATIN SMALL LETTER Y WITH LOOP
ɣ			ɣ		letter					U+0263: LATIN SMALL LETTER GAMMA
ɤ			ɤ		letter					U+0264: LATIN SMALL LETTER RAMS HORN
ꝩ			ꝩ		letter					U+A769: LATIN SMALL LETTER VEND
ʎ			ʎ		letter					U+028E: LATIN SMALL LETTER TURNED Y
ƛ			ƛ		letter					U+019B: LATIN SMALL LETTER LAMBDA WITH STROKE
ʸ			ʸ		letter					U+02B8: MODIFIER LETTER SMALL Y
ˠ			ˠ		letter					U+02E0: MODIFIER LETTER SMALL GAMMA
ᵞ			ᵞ		letter					U+1D5E: MODIFIER LETTER SMALL GREEK GAMMA
ʏ			ʏ		letter					U+028F: LATIN LETTER SMALL CAPITAL Y
ᵧ			ᵧ		letter					U+1D67: GREEK SUBSCRIPT SMALL LETTER GAMMA
z			z		letter					U+007A: LATIN SMALL LETTER Z
ź			ź		letter					U+017A: LATIN SMALL LETTER Z WITH ACUTE
ẑ			ẑ		letter					U+1E91: LATIN SMALL LETTER Z WITH CIRCUMFLEX
ž			ž		letter					U+017E: LATIN SMALL LETTER Z WITH CARON
ż			ż		letter					U+017C: LATIN SMALL LETTER Z WITH DOT ABOVE
ƶ			ƶ		letter					U+01B6: LATIN SMALL LETTER Z WITH STROKE
ᵶ			ᵶ		letter					U+1D76: LATIN SMALL LETTER Z WITH MIDDLE TILDE
ẓ			ẓ		letter					U+1E93: LATIN SMALL LETTER Z WITH DOT BELOW
ẕ			ẕ		letter					U+1E95: LATIN SMALL LETTER Z WITH LINE BELOW
ʐ			ʐ		letter					U+0290: LATIN SMALL LETTER Z WITH RETROFLEX HOOK
ᶎ			ᶎ		letter					U+1D8E: LATIN SMALL LETTER Z WITH PALATAL HOOK
ʑ			ʑ		letter					U+0291: LATIN SMALL LETTER Z WITH CURL
ȥ			ȥ		letter					U+0225: LATIN SMALL LETTER Z WITH HOOK
ⱬ			ⱬ		letter					U+2C6C: LATIN SMALL LETTER Z WITH DESCENDER
ɀ			ɀ		letter					U+0240: LATIN SMALL LETTER Z WITH SWASH TAIL
ʒ			ʒ		letter					U+0292: LATIN SMALL LETTER EZH
ǯ			ǯ		letter					U+01EF: LATIN SMALL LETTER EZH WITH CARON
ʓ			ʓ		letter					U+0293: LATIN SMALL LETTER EZH WITH CURL
ƺ			ƺ		letter					U+01BA: LATIN SMALL LETTER EZH WITH TAIL
ᶚ			ᶚ		letter					U+1D9A: LATIN SMALL LETTER EZH WITH RETROFLEX HOOK
ƹ			ƹ		letter					U+01B9: LATIN SMALL LETTER EZH REVERSED
ꝣ			ꝣ		letter					U+A763: LATIN SMALL LETTER VISIGOTHIC Z
ᵹ			ᵹ		letter					U+1D79: LATIN SMALL LETTER INSULAR G
ᶻ			ᶻ		letter					U+1DBB: MODIFIER LETTER SMALL Z
ᶼ			ᶼ		letter					U+1DBC: MODIFIER LETTER SMALL Z WITH RETROFLEX HOOK
ᶽ			ᶽ		letter					U+1DBD: MODIFIER LETTER SMALL Z WITH CURL
ᶾ			ᶾ		letter					U+1DBE: MODIFIER LETTER SMALL EZH
ᴢ			ᴢ		letter					U+1D22: LATIN LETTER SMALL CAPITAL Z
ᴣ			ᴣ		letter					U+1D23: LATIN LETTER SMALL CAPITAL EZH
ɂ			ɂ		letter					U+0242: LATIN SMALL LETTER GLOTTAL STOP
ʔ			ʔ		letter					U+0294: LATIN LETTER GLOTTAL STOP
ʡ			ʡ		letter					U+02A1: LATIN LETTER GLOTTAL STOP WITH STROKE
ʕ			ʕ		letter					U+0295: LATIN LETTER PHARYNGEAL VOICED FRICATIVE
ʢ			ʢ		letter					U+02A2: LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE
ʖ			ʖ		letter					U+0296: LATIN LETTER INVERTED GLOTTAL STOP
ƾ			ƾ		letter					U+01BE: LATIN LETTER INVERTED GLOTTAL STOP WITH STROKE
ˤ			ˤ		letter					U+02E4: MODIFIER LETTER SMALL REVERSED GLOTTAL STOP
ˀ			ˀ		letter					U+02C0: MODIFIER LETTER GLOTTAL STOP
ˁ			ˁ		letter					U+02C1: MODIFIER LETTER REVERSED GLOTTAL STOP
ˈ			ˈ		letter					U+02C8: MODIFIER LETTER VERTICAL LINE
ˉ			ˉ		letter					U+02C9: MODIFIER LETTER MACRON
ˑ			ˑ		letter					U+02D1: MODIFIER LETTER HALF TRIANGULAR COLON
ˊ			ˊ		letter					U+02CA: MODIFIER LETTER ACUTE ACCENT
ˋ			ˋ		letter					U+02CB: MODIFIER LETTER GRAVE ACCENT
ʹ			ʹ		letter					U+02B9: MODIFIER LETTER PRIME
ʺ			ʺ		letter					U+02BA: MODIFIER LETTER DOUBLE PRIME
ˆ			ˆ		letter					U+02C6: MODIFIER LETTER CIRCUMFLEX ACCENT
ˇ			ˇ		letter					U+02C7: CARON
ꜥ			ꜥ		letter					U+A725: LATIN SMALL LETTER EGYPTOLOGICAL AIN
ʻ			ʻ		letter					U+02BB: MODIFIER LETTER TURNED COMMA
ʼ			ʼ		letter					U+02BC: MODIFIER LETTER APOSTROPHE
ʽ			ʽ		letter					U+02BD: MODIFIER LETTER REVERSED COMMA
ˮ			ˮ		letter					U+02EE: MODIFIER LETTER DOUBLE APOSTROPHE
ᵔ			ᵔ		letter					U+1D54: MODIFIER LETTER SMALL TOP HALF O
ᵕ			ᵕ		letter					U+1D55: MODIFIER LETTER SMALL BOTTOM HALF O
ʾ			ʾ		letter					U+02BE: MODIFIER LETTER RIGHT HALF RING
ʿ			ʿ		letter					U+02BF: MODIFIER LETTER LEFT HALF RING
ᵠ			ᵠ		letter					U+1D60: MODIFIER LETTER SMALL GREEK PHI
ᵜ			ᵜ		letter					U+1D5C: MODIFIER LETTER SMALL AIN
ˌ			ˌ		letter					U+02CC: MODIFIER LETTER LOW VERTICAL LINE
ˍ			ˍ		letter					U+02CD: MODIFIER LETTER LOW MACRON
ˎ			ˎ		letter					U+02CE: MODIFIER LETTER LOW GRAVE ACCENT
ˏ			ˏ		letter					U+02CF: MODIFIER LETTER LOW ACUTE ACCENT
ꞈ			ꞈ		letter					U+A788: MODIFIER LETTER LOW CIRCUMFLEX ACCENT
ˬ			ˬ		letter					U+02EC: MODIFIER LETTER VOICING
ᵩ			ᵩ		letter					U+1D69: GREEK SUBSCRIPT SMALL LETTER PHI
ƻ			ƻ		letter					U+01BB: LATIN LETTER TWO WITH STROKE
ꝛ			ꝛ		letter					U+A75B: LATIN SMALL LETTER R ROTUNDA
ꜭ			ꜭ		letter					U+A72D: LATIN SMALL LETTER CUATRILLO
ꜯ			ꜯ		letter					U+A72F: LATIN SMALL LETTER CUATRILLO WITH COMMA
ꝝ			ꝝ		letter					U+A75D: LATIN SMALL LETTER RUM ROTUNDA
ƽ			ƽ		letter					U+01BD: LATIN SMALL LETTER TONE FIVE
ỽ			ỽ		letter					U+1EFD: LATIN SMALL LETTER MIDDLE-WELSH V
ȣ			ȣ		letter					U+0223: LATIN SMALL LETTER OU
ᴕ			ᴕ		letter					U+1D15: LATIN LETTER SMALL CAPITAL OU
ꝯ			ꝯ		letter					U+A76F: LATIN SMALL LETTER CON
ꝰ			ꝰ		letter					U+A770: MODIFIER LETTER US
µ			µ		letter					U+00B5: MICRO SIGN
ꝿ			ꝿ		letter					U+A77F: LATIN SMALL LETTER TURNED INSULAR G
ⱶ			ⱶ		letter					U+2C76: LATIN SMALL LETTER HALF H
ⱷ			ⱷ		letter					U+2C77: LATIN SMALL LETTER TAILLESS PHI
ꝸ			ꝸ		letter					U+A778: LATIN SMALL LETTER UM
ɷ			ɷ		letter					U+0277: LATIN SMALL LETTER CLOSED OMEGA
ɸ			ɸ		letter					U+0278: LATIN SMALL LETTER PHI
ʘ			ʘ		letter					U+0298: LATIN LETTER BILABIAL CLICK
ʚ			ʚ		letter					U+029A: LATIN SMALL LETTER CLOSED OPEN E
ʭ			ʭ		letter					U+02AD: LATIN LETTER BIDENTAL PERCUSSIVE
ᴖ			ᴖ		letter					U+1D16: LATIN SMALL LETTER TOP HALF O
ᴗ			ᴗ		letter					U+1D17: LATIN SMALL LETTER BOTTOM HALF O
ᴤ			ᴤ		letter					U+1D24: LATIN LETTER VOICED LARYNGEAL SPIRANT
ᴥ			ᴥ		letter					U+1D25: LATIN LETTER AIN
ᴦ			ᴦ		letter					U+1D26: GREEK LETTER SMALL CAPITAL GAMMA
ᴨ			ᴨ		letter					U+1D28: GREEK LETTER SMALL CAPITAL PI
ᴪ			ᴪ		letter					U+1D2A: GREEK LETTER SMALL CAPITAL PSI
ᴫ			ᴫ		letter					U+1D2B: CYRILLIC LETTER SMALL CAPITAL EL
ꞌ			ꞌ		letter					U+A78C: LATIN SMALL LETTER SALTILLO
ǀ			ǀ		letter					U+01C0: LATIN LETTER DENTAL CLICK
ǁ			ǁ		letter					U+01C1: LATIN LETTER LATERAL CLICK
ǂ			ǂ		letter					U+01C2: LATIN LETTER ALVEOLAR CLICK
ǃ			ǃ		letter					U+01C3: LATIN LETTER RETROFLEX CLICK
ꭅ			ꭅ		letter					U+AB45: LATIN SMALL LETTER STIRRUP R
ː			ː		letter					U+02D0: MODIFIER LETTER TRIANGULAR COLON
ꞏ			ꞏ		letter					U+A78F: LATIN LETTER SINOLOGICAL DOT
										
										
										
										
ͣ			ͣ		mark					U+0363: COMBINING LATIN SMALL LETTER A​
ͨ			ͨ		mark					U+0368: COMBINING LATIN SMALL LETTER C​
ͩ			ͩ		mark					U+0369: COMBINING LATIN SMALL LETTER D​
ͤ			ͤ		mark					U+0364: COMBINING LATIN SMALL LETTER E​
ͪ			ͪ		mark					U+036A: COMBINING LATIN SMALL LETTER H​
ͥ			ͥ		mark					U+0365: COMBINING LATIN SMALL LETTER I​
ͫ			ͫ		mark					U+036B: COMBINING LATIN SMALL LETTER M​
ͦ			ͦ		mark					U+0366: COMBINING LATIN SMALL LETTER O​
ͬ			ͬ		mark					U+036C: COMBINING LATIN SMALL LETTER R​
ͭ			ͭ		mark					U+036D: COMBINING LATIN SMALL LETTER T​
ͧ			ͧ		mark					U+0367: COMBINING LATIN SMALL LETTER U​
ͮ			ͮ		mark					U+036E: COMBINING LATIN SMALL LETTER V​
̀			̀		mark					U+0300: COMBINING GRAVE ACCENT​
̀			̀		mark					U+0300: COMBINING GRAVE ACCENT​
̏			̏		mark					U+030F: COMBINING DOUBLE GRAVE ACCENT​
́			́		mark					U+0301: COMBINING ACUTE ACCENT​
́			́		mark					U+0301: COMBINING ACUTE ACCENT​
̋			̋		mark					U+030B: COMBINING DOUBLE ACUTE ACCENT​
̍			̍		mark					U+030D: COMBINING VERTICAL LINE ABOVE​
̎			̎		mark					U+030E: COMBINING DOUBLE VERTICAL LINE ABOVE​
̾			̾		mark					U+033E: COMBINING VERTICAL TILDE​
̂			̂		mark					U+0302: COMBINING CIRCUMFLEX ACCENT​
̌			̌		mark					U+030C: COMBINING CARON​
͐			͐		mark					U+0350: COMBINING RIGHT ARROWHEAD ABOVE​
̆			̆		mark					U+0306: COMBINING BREVE​
̑			̑		mark					U+0311: COMBINING INVERTED BREVE​
͑			͑		mark					U+0351: COMBINING LEFT HALF RING ABOVE​
͗			͗		mark					U+0357: COMBINING RIGHT HALF RING ABOVE​
̃			̃		mark					U+0303: COMBINING TILDE​
͂			͂		mark					U+0342: COMBINING GREEK PERISPOMENI​
͊			͊		mark					U+034A: COMBINING NOT TILDE ABOVE​
͋			͋		mark					U+034B: COMBINING HOMOTHETIC ABOVE​
͌			͌		mark					U+034C: COMBINING ALMOST EQUAL TO ABOVE​
̄			̄		mark					U+0304: COMBINING MACRON​
̅			̅		mark					U+0305: COMBINING OVERLINE​
̿			̿		mark					U+033F: COMBINING DOUBLE OVERLINE​
̇			̇		mark					U+0307: COMBINING DOT ABOVE​
̈			̈		mark					U+0308: COMBINING DIAERESIS​
̊			̊		mark					U+030A: COMBINING RING ABOVE​
̉			̉		mark					U+0309: COMBINING HOOK ABOVE​
̒			̒		mark					U+0312: COMBINING TURNED COMMA ABOVE​
̓			̓		mark					U+0313: COMBINING COMMA ABOVE​
̓			̓		mark					U+0313: COMBINING COMMA ABOVE​
̔			̔		mark					U+0314: COMBINING REVERSED COMMA ABOVE​
̕			̕		mark					U+0315: COMBINING COMMA ABOVE RIGHT​
̛			̛		mark					U+031B: COMBINING HORN​
̚			̚		mark					U+031A: COMBINING LEFT ANGLE ABOVE​
͆			͆		mark					U+0346: COMBINING BRIDGE ABOVE​
̽			̽		mark					U+033D: COMBINING X ABOVE​
̐			̐		mark					U+0310: COMBINING CANDRABINDU​
͒			͒		mark					U+0352: COMBINING FERMATA​
́			́		mark					U+0301: COMBINING ACUTE ACCENT​
͝			͝		mark					U+035D: COMBINING DOUBLE BREVE​
͞			͞		mark					U+035E: COMBINING DOUBLE MACRON​
͠			͠		mark					U+0360: COMBINING DOUBLE TILDE​
͡			͡		mark					U+0361: COMBINING DOUBLE INVERTED BREVE​
̴			̴		mark					U+0334: COMBINING TILDE OVERLAY​
̵			̵		mark					U+0335: COMBINING SHORT STROKE OVERLAY​
̶			̶		mark					U+0336: COMBINING LONG STROKE OVERLAY​
̷			̷		mark					U+0337: COMBINING SHORT SOLIDUS OVERLAY​
̸			̸		mark					U+0338: COMBINING LONG SOLIDUS OVERLAY​
̖			̖		mark					U+0316: COMBINING GRAVE ACCENT BELOW​
̗			̗		mark					U+0317: COMBINING ACUTE ACCENT BELOW​
̩			̩		mark					U+0329: COMBINING VERTICAL LINE BELOW​
͈			͈		mark					U+0348: COMBINING DOUBLE VERTICAL LINE BELOW​
̭			̭		mark					U+032D: COMBINING CIRCUMFLEX ACCENT BELOW​
̬			̬		mark					U+032C: COMBINING CARON BELOW​
͔			͔		mark					U+0354: COMBINING LEFT ARROWHEAD BELOW​
͕			͕		mark					U+0355: COMBINING RIGHT ARROWHEAD BELOW​
͖			͖		mark					U+0356: COMBINING RIGHT ARROWHEAD AND UP ARROWHEAD BELOW​
̮			̮		mark					U+032E: COMBINING BREVE BELOW​
̯			̯		mark					U+032F: COMBINING INVERTED BREVE BELOW​
̜			̜		mark					U+031C: COMBINING LEFT HALF RING BELOW​
̹			̹		mark					U+0339: COMBINING RIGHT HALF RING BELOW​
̰			̰		mark					U+0330: COMBINING TILDE BELOW​
̼			̼		mark					U+033C: COMBINING SEAGULL BELOW​
̱			̱		mark					U+0331: COMBINING MACRON BELOW​
̠			̠		mark					U+0320: COMBINING MINUS SIGN BELOW​
̲			̲		mark					U+0332: COMBINING LOW LINE​
̳			̳		mark					U+0333: COMBINING DOUBLE LOW LINE​
͇			͇		mark					U+0347: COMBINING EQUALS SIGN BELOW​
̣			̣		mark					U+0323: COMBINING DOT BELOW​
̤			̤		mark					U+0324: COMBINING DIAERESIS BELOW​
̥			̥		mark					U+0325: COMBINING RING BELOW​
̻			̻		mark					U+033B: COMBINING SQUARE BELOW​
̧			̧		mark					U+0327: COMBINING CEDILLA​
̨			̨		mark					U+0328: COMBINING OGONEK​
ͅ			ͅ		mark					U+0345: COMBINING GREEK YPOGEGRAMMENI​
̦			̦		mark					U+0326: COMBINING COMMA BELOW​
̡			̡		mark					U+0321: COMBINING PALATALIZED HOOK BELOW​
̢			̢		mark					U+0322: COMBINING RETROFLEX HOOK BELOW​
͉			͉		mark					U+0349: COMBINING LEFT ANGLE BELOW​
̪			̪		mark					U+032A: COMBINING BRIDGE BELOW​
̺			̺		mark					U+033A: COMBINING INVERTED BRIDGE BELOW​
̫			̫		mark					U+032B: COMBINING INVERTED DOUBLE ARCH BELOW​
̘			̘		mark					U+0318: COMBINING LEFT TACK BELOW​
̙			̙		mark					U+0319: COMBINING RIGHT TACK BELOW​
̝			̝		mark					U+031D: COMBINING UP TACK BELOW​
̞			̞		mark					U+031E: COMBINING DOWN TACK BELOW​
̟			̟		mark					U+031F: COMBINING PLUS SIGN BELOW​
͓			͓		mark					U+0353: COMBINING X BELOW​
͍			͍		mark					U+034D: COMBINING LEFT RIGHT ARROW BELOW​
͎			͎		mark					U+034E: COMBINING UPWARDS ARROW BELOW​
͟			͟		mark					U+035F: COMBINING DOUBLE MACRON BELOW​
͢			͢		mark					U+0362: COMBINING DOUBLE RIGHTWARDS ARROW BELOW​
										
										
										
¼			¼		number					U+00BC: VULGAR FRACTION ONE QUARTER
½			½		number					U+00BD: VULGAR FRACTION ONE HALF
¾			¾		number					U+00BE: VULGAR FRACTION THREE QUARTERS
₀			₀		number					U+2080: SUBSCRIPT ZERO
₁			₁		number					U+2081: SUBSCRIPT ONE
₂			₂		number					U+2082: SUBSCRIPT TWO
₃			₃		number					U+2083: SUBSCRIPT THREE
₄			₄		number					U+2084: SUBSCRIPT FOUR
₅			₅		number					U+2085: SUBSCRIPT FIVE
₆			₆		number					U+2086: SUBSCRIPT SIX
₇			₇		number					U+2087: SUBSCRIPT SEVEN
₈			₈		number					U+2088: SUBSCRIPT EIGHT
₉			₉		number					U+2089: SUBSCRIPT NINE
⁰			⁰		number					U+2070: SUPERSCRIPT ZERO
¹			¹		number					U+00B9: SUPERSCRIPT ONE
²			²		number					U+00B2: SUPERSCRIPT TWO
³			³		number					U+00B3: SUPERSCRIPT THREE
⁴			⁴		number					U+2074: SUPERSCRIPT FOUR
⁵			⁵		number					U+2075: SUPERSCRIPT FIVE
⁶			⁶		number					U+2076: SUPERSCRIPT SIX
⁷			⁷		number					U+2077: SUPERSCRIPT SEVEN
⁸			⁸		number					U+2078: SUPERSCRIPT EIGHT
⁹			⁹		number					U+2079: SUPERSCRIPT NINE
										
										
										
•			•		punctuation					U+2022: BULLET
¿			¿		punctuation					U+00BF: INVERTED QUESTION MARK
⁽			⁽		punctuation					U+207D: SUPERSCRIPT LEFT PARENTHESIS
⁾			⁾		punctuation					U+207E: SUPERSCRIPT RIGHT PARENTHESIS
·			·		punctuation					U+00B7: MIDDLE DOT
₍			₍		punctuation					U+208D: SUBSCRIPT LEFT PARENTHESIS
₎			₎		punctuation					U+208E: SUBSCRIPT RIGHT PARENTHESIS
§			§		punctuation					U+00A7: SECTION SIGN
⁋			⁋		punctuation					U+204B: REVERSED PILCROW SIGN
¡			¡		punctuation					U+00A1: INVERTED EXCLAMATION MARK
‐			‐		punctuation					U+2010: HYPHEN
‑			‑		punctuation					U+2011: NON-BREAKING HYPHEN
‒			‒		punctuation					U+2012: FIGURE DASH
†			†		punctuation					U+2020: DAGGER
‡			‡		punctuation					U+2021: DOUBLE DAGGER
‣			‣		punctuation					U+2023: TRIANGULAR BULLET
‰			‰		punctuation					U+2030: PER MILLE SIGN
‸			‸		punctuation					U+2038: CARET
‹			‹		punctuation					U+2039: SINGLE LEFT-POINTING ANGLE QUOTATION MARK
›			›		punctuation					U+203A: SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
‽			‽		punctuation					U+203D: INTERROBANG
‿			‿		punctuation					U+203F: UNDERTIE
⁃			⁃		punctuation					U+2043: HYPHEN BULLET
										
										
										
¢			¢		symbol					U+00A2: CENT SIGN
©			©		symbol					U+00A9: COPYRIGHT SIGN
∅			∅		symbol					U+2205: EMPTY SET
®			®		symbol					U+00AE: REGISTERED SIGN
×			×		symbol					U+00D7: MULTIPLICATION SIGN
˟			˟		symbol					U+02DF: MODIFIER LETTER CROSS ACCENT
¥			¥		symbol					U+00A5: YEN SIGN
˞			˞		symbol					U+02DE: MODIFIER LETTER RHOTIC HOOK
¯			¯		symbol					U+00AF: MACRON
⁻			⁻		symbol					U+207B: SUPERSCRIPT MINUS
⁼			⁼		symbol					U+207C: SUPERSCRIPT EQUALS SIGN
˭			˭		symbol					U+02ED: MODIFIER LETTER UNASPIRATED
˴			˴		symbol					U+02F4: MODIFIER LETTER MIDDLE GRAVE ACCENT
˵			˵		symbol					U+02F5: MODIFIER LETTER MIDDLE DOUBLE GRAVE ACCENT
˶			˶		symbol					U+02F6: MODIFIER LETTER MIDDLE DOUBLE ACUTE ACCENT
˝			˝		symbol					U+02DD: DOUBLE ACUTE ACCENT
´			´		symbol					U+00B4: ACUTE ACCENT
˜			˜		symbol					U+02DC: SMALL TILDE
꜠			꜠		symbol					U+A720: MODIFIER LETTER STRESS AND HIGH TONE
꜡			꜡		symbol					U+A721: MODIFIER LETTER STRESS AND LOW TONE
˂			˂		symbol					U+02C2: MODIFIER LETTER LEFT ARROWHEAD
˃			˃		symbol					U+02C3: MODIFIER LETTER RIGHT ARROWHEAD
˄			˄		symbol					U+02C4: MODIFIER LETTER UP ARROWHEAD
˅			˅		symbol					U+02C5: MODIFIER LETTER DOWN ARROWHEAD
⁺			⁺		symbol					U+207A: SUPERSCRIPT PLUS SIGN
˖			˖		symbol					U+02D6: MODIFIER LETTER PLUS SIGN
˟			˟		symbol					U+02DF: MODIFIER LETTER CROSS ACCENT
˗			˗		symbol					U+02D7: MODIFIER LETTER MINUS SIGN
¬			¬		symbol					U+00AC: NOT SIGN
˪			˪		symbol					U+02EA: MODIFIER LETTER YIN DEPARTING TONE MARK
˫			˫		symbol					U+02EB: MODIFIER LETTER YANG DEPARTING TONE MARK
˹			˹		symbol					U+02F9: MODIFIER LETTER BEGIN HIGH TONE
˺			˺		symbol					U+02FA: MODIFIER LETTER END HIGH TONE
˘			˘		symbol					U+02D8: BREVE
°			°		symbol					U+00B0: DEGREE SIGN
˚			˚		symbol					U+02DA: RING ABOVE
˙			˙		symbol					U+02D9: DOT ABOVE
¨			¨		symbol					U+00A8: DIAERESIS
¸			¸		symbol					U+00B8: CEDILLA
˛			˛		symbol					U+02DB: OGONEK
˯			˯		symbol					U+02EF: MODIFIER LETTER LOW DOWN ARROWHEAD
˰			˰		symbol					U+02F0: MODIFIER LETTER LOW UP ARROWHEAD
˱			˱		symbol					U+02F1: MODIFIER LETTER LOW LEFT ARROWHEAD
˲			˲		symbol					U+02F2: MODIFIER LETTER LOW RIGHT ARROWHEAD
˳			˳		symbol					U+02F3: MODIFIER LETTER LOW RING
˷			˷		symbol					U+02F7: MODIFIER LETTER LOW TILDE
˻			˻		symbol					U+02FB: MODIFIER LETTER BEGIN LOW TONE
˼			˼		symbol					U+02FC: MODIFIER LETTER END LOW TONE
˽			˽		symbol					U+02FD: MODIFIER LETTER SHELF
˾			˾		symbol					U+02FE: MODIFIER LETTER OPEN SHELF
˿			˿		symbol					U+02FF: MODIFIER LETTER LOW LEFT ARROW
˔			˔		symbol					U+02D4: MODIFIER LETTER UP TACK
˕			˕		symbol					U+02D5: MODIFIER LETTER DOWN TACK
₊			₊		symbol					U+208A: SUBSCRIPT PLUS SIGN
₋			₋		symbol					U+208B: SUBSCRIPT MINUS
₌			₌		symbol					U+208C: SUBSCRIPT EQUALS SIGN
£			£		symbol					U+00A3: POUND SIGN
¦			¦		symbol					U+00A6: BROKEN BAR
˥			˥		symbol					U+02E5: MODIFIER LETTER EXTRA-HIGH TONE BAR
˦			˦		symbol					U+02E6: MODIFIER LETTER HIGH TONE BAR
˧			˧		symbol					U+02E7: MODIFIER LETTER MID TONE BAR
˨			˨		symbol					U+02E8: MODIFIER LETTER LOW TONE BAR
˩			˩		symbol					U+02E9: MODIFIER LETTER EXTRA-LOW TONE BAR
꭛			꭛		symbol					U+AB5B: MODIFIER BREVE WITH INVERTED BREVE
±			±		symbol					U+00B1: PLUS-MINUS SIGN
÷			÷		symbol					U+00F7: DIVISION SIGN
꞊			꞊		symbol					U+A78A: MODIFIER LETTER SHORT EQUALS SIGN
¤			¤		symbol					U+00A4: CURRENCY SIGN
꞉			꞉		symbol					U+A789: MODIFIER LETTER COLON
˸			˸		symbol					U+02F8: MODIFIER LETTER RAISED COLON
˒			˒		symbol					U+02D2: MODIFIER LETTER CENTRED RIGHT HALF RING
˓			˓		symbol					U+02D3: MODIFIER LETTER CENTRED LEFT HALF RING
⁄			⁄		symbol					U+2044: FRACTION SLASH
←			←		symbol					U+2190: LEFTWARDS ARROW
→			→		symbol					U+2192: RIGHTWARDS ARROW
`




var cols = {
"class": 1,
"key":2,
"transLoc": 3,
"ipaLoc": 0,
"transckey": 0,
"transcription": 0,
"typeLoc": 5,
"statusLoc": 0,
"equiv": 0,
"dvowel": 0,
"ivowel": 0,
"subj":0,
"ltone":0,
"htone":0,
"lc":0,
"uc":0,
"meaning":0,
"shape": 0,
"numLoc": 0,
"nameLoc": 0,
"nnameLoc": 0,
"ucsName": 10,

//"othertranscriptions": [[6, 'ISO 15919']]
}



